### PR TITLE
Linux 6.1.11

### PR DESCRIPTION
**Pull request by 13r0ck**

### CODE REVIEW

**Comment by leviport** [comment]
MST looks good on Dev One with this kernel :tada:

**Review by jackpot51 — APPROVED** [review]

**Review by n3m0-22 — COMMENTED** [review]
### Pop 22.04 Testing  

 - Passed all testing:
   - [x] `lemp11`
   - [x] `Dev One`  
 
 - Passed (*not including NVIDIA 470*):
   - [x] `gaze15`
   - [x] `oryp4`
   
Notes:
The current 470 driver as well as the 515 in `pop-shop` are not working. The updated 470 driver in PR https://github.com/pop-os/nvidia-graphics-drivers-470/pull/12 works, but will need further testing before approval.

*Testing on Ubuntu now*

[kernel_testing.txt](https://github.com/pop-os/linux/files/10726734/kernel_testing.txt)

**Comment by XV-02** [comment]
I can corroborate that on a Gaze16-3060-B, nvidia515 and nvidia-470 encounter dkms errors during install, and that https://github.com/pop-os/nvidia-graphics-drivers-470/pull/12 fixes the issue for the 470 drivers.

**Comment by XV-02** [comment]
I'm no longer seeing the Nvidia/Plymouth issue where the system gets stuck displaying the splash screen. And, the kernel looks fine on a Mira B3 with Nvidia (driver 525)

**Comment by leviport** [comment]
We have to figure out what to do about 515, but I think this is just about ready to go once we sort that out. I tried fixing it here, but didn't quite get it: https://github.com/pop-os/nvidia-graphics-drivers-515/pull/1

Since 515 is no longer listed on Nvidia's download page, and 525 has been around a while, turning 515 into a 525 transitionary package is probably acceptable as well. Either way, we just need it to not be broken the way it currently is.

**Comment by 13r0ck** [comment]
https://github.com/pop-os/nvidia-graphics-drivers/pull/177 should fix that issue

**Review by leviport — APPROVED** [review]
Now that Nvidia 515 is resolved, this should be ready to go.

**Pull request merged**
