### PR TITLE
Linux 6.4.10 jammy

### LINKED ISSUE #269: HP Dev One resolution options are only 1080p on 6.4.6 kernel
After upgrading to the 6.4.6 kernel only 1080p is available on the Dev One. Works correctly if booting to oldkern which is 6.2.6.

Screenshot from 2023-08-05 23-57-07

xrandr output:

```
Screen 0: minimum 320 x 200, current 3072 x 1728, maximum 16384 x 16384
eDP connected primary 3072x1728+0+0 (normal left inverted right x axis y axis) 309mm x 174mm
   1920x1080     60.01*+
HDMI-A-0 disconnected (normal left inverted right x axis y axis)
DisplayPort-0 disconnected (normal left inverted right x axis y axis)
DisplayPort-1 disconnected (normal left inverted right x axis y axis)
```

### LINKED ISSUE #272: Inception and Downfall fixes to PopOS Kernel
First off--thank you for a wonderful distro; I've been extremely happy with the results of everyone's hard work.

Read today about the new vulnerabilities affected Zen 3 & 4, which pertain to me directory: [(Phoronix) Six New Stable Linux Kernel Updates For Intel DOWNFALL & AMD INCEPTION](https://www.phoronix.com/news/New-Linux-Stable-Downfall) I've been looking around the web for updates on when this would get passed upstream into Ubuntu and eventually PopOS--or is this fix already in the recent `6.4.6-76060406-generic` kernal from your team? Eager to learn more about the progress of this work. Thanks again!

### PR DESCRIPTION
**Pull request by mmstick**
Supersedes #271 

Closes #269 
Closes #272

### CODE REVIEW

**Review by jackpot51 — APPROVED** [review]

**Comment by XV-02** [comment]
Looks like `virtualbox-dkms` isn't playing nice with 6.4.10, so we'll have to remedy that first.

**Comment by Simbaclaws** [comment]
I'm not sure if I should mention this here, but I found out that my oryx pro 4 b, after updating to kernel 6.4.x has issues with displaying any output. Only when I set nomodeset in the kernel parameters am I able to boot up on kernel 6.4.x.

Kernel 6.2.x doesn't exhibit this problem. This problem also occurs on other distributions using kernel 6.4.x

If anyone of your team is able to reproduce it on their machines, it would be nice if someone could take a look at it.

I can also give a dmesg log of the nvidia card crashing on kernel 6.4.x if you are interested.
Please let me know if there is anything I can do to help.

**Comment by leviport** [comment]
@Simbaclaws Please open an issue, rather than posting a comment in a PR: https://github.com/pop-os/linux/issues

**Comment by Simbaclaws** [comment]
Apologies, will do

**Pull request closed without merging**
