### PR TITLE
Linux 5.19.5

### PR DESCRIPTION
**Pull request by 13r0ck**
@pop-os/quality-assurance  please check for mira-3 and pang11 issue

### CODE REVIEW

**Comment by n3m0-22** [comment]
Tested on `lemp11` and `framework` 11th Gen Intel. All testing passed with the exception of 150 `fwts s3` suspend on the `lemp11`. I manually tested suspend on the `lemp11` with and without a bluetooth device paired and connected. It is working the same as before with no regressions.

[5.19.5-testing-lemp11.txt](https://github.com/pop-os/linux/files/9473753/5.19.5-testing-lemp11.txt)

[5.19.5-testing-framework.txt](https://github.com/pop-os/linux/files/9473754/5.19.5-testing-framework.txt)

**Comment by gangwerz** [comment]
This kernel has passed testing on the galp5-1650Ti

No new issues, but I continue to be unable to open Steam from the app menu on Ubuntu.

[5.19.5-galp5-1650Ti.txt](https://github.com/pop-os/linux/files/9480535/5.19.5-galp5-1650Ti.txt)

**Comment by linuxgnuru** [comment]
Passed Pop 22.04 on pang11

# Kernel Releases Tests
Make a copy of this checklist for each OS version that the kernel will be released on (if merging into `master`, test Ubuntu LTS, Pop!\_OS LTS, and latest Pop!\_OS STS)

- [x] Updating to new kernel works with `apt update && apt upgrade`
    - [x] No new dependencies are required for kernel update
- [x] Mic in
- [x] Audio out:
    - [x] Laptop's built-in speakers
    - [x] Headphones
    - [x] HDMI
- [x] Video out via:
    - [x] HDMI
- [x] Suspend and resume:
    - [x] Suspend and resume works with a bluetooth device paired
    - [x] 150 suspend/resume cycles (`fwts s3 --s3-multiple 150`)
- [x] Graphics drivers included in the kernel (Intel/AMD)
- [x] Steam
    - [x] Steam installs via the Pop!_OS .deb in Pop!_Shop
    - [x] Steam launches from launcher
    - [x] Linux native game installs and runs
    - [x] Proton game installs and runs
- [x] VirtualBox installs and works as expected
- [x] Broadcom wireless driver (`bcmwl-kernel-source`) installs without DKMS errors

**Comment by bflanagin** [comment]
Passed Pop 22.04 on gaze15 (existing install)

# Kernel Releases Tests
Make a copy of this checklist for each OS version that the kernel will be released on (if merging into `master`, test Ubuntu LTS, Pop!\_OS LTS, and latest Pop!\_OS STS)

- [x] Updating to new kernel works with `apt update && apt upgrade`
    - [x] No new dependencies are required for kernel update
- [x] Mic in
- [x] Audio out:
    - [x] Laptop's built-in speakers
    - [x] Headphones
    - [x] HDMI
- [x] Video out via:
    - [x] HDMI
    - [x] DP
    - [ ] USB C
- [x] Suspend and resume:
    - [x] Suspend and resume works with a bluetooth device paired
    - [x] 150 suspend/resume cycles (`fwts s3 --s3-multiple 150`)
- [x] Graphics drivers included in the kernel (Intel/AMD)
- [x] Nvidia drivers install and function without issue
- [x] Steam
    - [ ] Steam installs via the Pop!_OS .deb in Pop!_Shop (Already installed)
    - [x] Steam launches from launcher
    - [x] Linux native game installs and runs
    - [x] Proton game installs and runs
- [x] VirtualBox installs and works as expected

**Comment by bflanagin** [comment]
Passed Pop 22.04 on gaze15 (existing install)

# Kernel Releases Tests
Make a copy of this checklist for each OS version that the kernel will be released on (if merging into `master`, test Ubuntu LTS, Pop!\_OS LTS, and latest Pop!\_OS STS)

- [x] Updating to new kernel works with `apt update && apt upgrade`
    - [x] No new dependencies are required for kernel update
- [x] Mic in
- [x] Audio out:
    - [x] Laptop's built-in speakers
    - [x] Headphones
    - [x] HDMI
- [x] Video out via:
    - [x] HDMI
    - [x] DP
    - [x] USB C
- [x] Suspend and resume:
    - [x] Suspend and resume works with a bluetooth device paired
    - [x] 150 suspend/resume cycles (`fwts s3 --s3-multiple 150`)
- [x] Graphics drivers included in the kernel (Intel/AMD)
- [x] Nvidia drivers install and function without issue
- [x] Steam
    - [ ] Steam installs via the Pop!_OS .deb in Pop!_Shop (Already installed)
    - [x] Steam launches from launcher
    - [x] Linux native game installs and runs
    - [x] Proton game installs and runs
- [x] VirtualBox installs and works as expected

**Comment by linuxgnuru** [comment]
Passed pang11 Ubuntu 22.04.1

# Kernel Releases Tests
Make a copy of this checklist for each OS version that the kernel will be released on (if merging into `master`, test Ubuntu LTS, Pop!\_OS LTS, and latest Pop!\_OS STS)

- [x] Updating to new kernel works with `apt update && apt upgrade`
    - [x] No new dependencies are required for kernel update
- [x] Mic in
- [x] Audio out:
    - [x] Laptop's built-in speakers
    - [x] Headphones
    - [x] HDMI
- [x ] Video out via:
    - [x] HDMI
- [x] Suspend and resume:
    - [x] Suspend and resume works with a bluetooth device paired
- [x] Graphics drivers included in the kernel (Intel/AMD)
- [x] Steam
    - [x] Steam installs
    - [x] Steam launches from dock
    - [x] Linux native game installs and runs
    - [x] Proton game installs and runs
- [x] VirtualBox installs and works as expected
- [x] Broadcom wireless driver (`bcmwl-kernel-source`) installs without DKMS errors

**Comment by XV-02** [comment]
Thelio Mega R2 - Both Pop!_OS 22.04 and Ubuntu 22.04 - passed:

# Kernel Releases Tests

- [x] Updating to new kernel works with `apt update && apt upgrade`
    - [x] No new dependencies are required for kernel update
- [x] Mic in
- [x] Audio out:
    - [x] Headphones
    - [x] DisplayPort
    - [x] HDMI
- [ ] Video out via:
    - [x] DisplayPort
    - [x] HDMI
- [x] Suspend and resume:
    - [x] Suspend and resume works with a bluetooth device paired
    - [x] Nvidia desktop
        - [x] Current Nvidia driver works (i.e. 510)
        - [x] Legacy Nvidia driver works (i.e. 470)
    - [x] Discrete AMD desktop
    - [x] 150 suspend/resume cycles (`fwts s3 --s3-multiple 150`)
- [x] Steam
    - [x] Steam installs via the Pop!_OS .deb in Pop!_Shop
    - [x] Steam launches from launcher
    - [x] Linux native game installs and runs
    - [X] Proton game installs and runs
- [x] VirtualBox installs and works as expected

**Comment by linuxgnuru** [comment]
HP Devone Pop! 22.04 - passed:

 # Kernel Releases Tests
Make a copy of this checklist for each OS version that the kernel will be released on (if merging into `master`, test Ubuntu LTS, Pop!\_OS LTS, and latest Pop!\_OS STS)

- [x] Updating to new kernel works with `apt update && apt upgrade`
    - [x] No new dependencies are required for kernel update
- [x] `system76-power` still operates as expected (across Intel/NVIDIA/switchable machines)
- [x] Mic in
- [x] Audio out:
    - [x] Laptop's built-in speakers
    - [x] Headphones
    - [x] HDMI
- [x] Video out via:
    - [x] HDMI
- [x] Suspend and resume:
    - [x] Suspend and resume works with a bluetooth device paired
    - [x] 150 suspend/resume cycles (`fwts s3 --s3-multiple 150`)
- [x] Graphics drivers included in the kernel (Intel/AMD)
- [x] Steam
    - [x] Steam installs via the Pop!_OS .deb in Pop!_Shop
    - [x] Steam launches from launcher
    - [x] Linux native game installs and runs
    - [x] Proton game installs and runs
- [x] VirtualBox installs and works as expected
- [x] Broadcom wireless driver (`bcmwl-kernel-source`) installs without DKMS errors

**Comment by jackpot51** [comment]
This will need to have #177 cherry picked

**Comment by 13r0ck** [comment]
#177 has been cherry-picked

**Comment by Seibz** [comment]
Just checking in here, regarding testing firmware. My pangolin pang10 had a firmware update to 1.07.08 recently...have we tested the pang10 and pang11's new firmware against this kernel update? Just wondering.

**Comment by jackpot51** [comment]
> #177 has been cherry-picked

Have to drop #177 and pick #178 instead now

**Comment by jackpot51** [comment]
Closing because I will prep 5.19.10 with #178

**Comment by rvprasad** [comment]
Compared to 5.18.10-76051810-generic, 5.19.0-76051900-generic seems to consistently trigger RCU stalls during system initialization after kernel booting on an Oryx Pro 3.  Anyone else observing such issues?

**Comment by leviport** [comment]
This is a closed pull request that was never merged. This is not the place to report bugs.

**Pull request closed without merging**
