### PR TITLE
Linux 5.18.4

### PR DESCRIPTION
**Pull request by jackpot51**
https://cdn.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.18.4

Please test the following:
- [ ] Bluetooth suspend - Workaround in pop-default-settings
- [ ] NVIDIA 470: https://github.com/pop-os/nvidia-graphics-drivers-470/pull/7
- [ ] NVIDIA 510: Related to https://github.com/NVIDIA/open-gpu-kernel-modules/issues/256, should work now that I disabled `CONFIG_X86_KERNEL_IBT`
- [ ] VirtualBox - Already updated to support 5.18
- [ ] ZFS - Needs new version

### CODE REVIEW

**Comment by jackpot51** [comment]
@linuxgnuru correct. I am working on backporting fixes from zfs to work around that.

**Comment by n3m0-22** [comment]
I'm having issues with Virtualbox on both 22.04 and 21.10. The display of the VM keeps reloading similar to what you see when restarting GNOME. This happens with a fresh install of a VM as well as existing ones. It is made worse by installing VboxGuestAddtions. 

Example with host 21.10 and guest 22.04


https://user-images.githubusercontent.com/11048214/174196952-50e721a0-67ba-4800-be6f-1ac0982c100f.mp4

**Comment by jackpot51** [comment]
Marking this as a draft until a new ZFS comes out.

**Comment by jackpot51** [comment]
Closed, #157 has upstream security fixes

**Pull request closed without merging**
