### PR TITLE
Linux 6.3

### PR DESCRIPTION
**Pull request by 13r0ck**

### CODE REVIEW

**Review by n3m0-22 — CHANGES_REQUESTED** [review]
I'm seeing DKMS errors with ZFS and Virtualbox.

[zfs-dkms-error.txt](https://github.com/pop-os/linux/files/11324423/zfs-dkms-error.txt)
[virtualbox-dkms-error.txt](https://github.com/pop-os/linux/files/11324426/virtualbox-dkms-error.txt)

**Comment by 13r0ck** [comment]
@n3m0-22 
https://github.com/pop-os/zfs-linux/pull/15
https://github.com/pop-os/virtualbox/pull/8
https://github.com/pop-os/virtualbox-ext-pack/pull/2

**Comment by leviport** [comment]
I saw a few hard freezes on my oryp9 while running this kernel. I booted oldkern to finish out the workday, and I haven't seen one since then. I'll investigate more tomorrow to see if I can find any clues.

**Comment by 13r0ck** [comment]
Oof, ya zfs isnt ready, and virtualbox 7.0.8 seems to have upstream packaging issues.
This one might have come out of the oven a bit early.

**Comment by leviport** [comment]
I think my freezing problem on oryp9 is related to using a USB-C display. I was in 6.3 this morning for a few hours without the second monitor and everything was fine. After about 10 minutes of being plugged into the display (USB-C DisplayPort, with 2 USB devices attached, and oryp9 was in Nvidia mode), I got another hard freeze that I couldn't get out of without REISUB.

**Comment by 13r0ck** [comment]
Yaaaa, lets skip this one

**Comment by pktiuk** [comment]
> Yaaaa, lets skip this one

Does it mean, that Pop!_OS won't get 6.3 kernel?

**Comment by mmstick** [comment]
@pktiuk It means we will not release 6.3.**0**

**Comment by jglathe** [comment]
Testing on 6.3.3. Weird issues with Remmina and snap (resullting in hard freezes). Installed the deb packages instead, seems to work nice. Nvidia, 2 monitors, sound via hdmi (?).

**Comment by pktiuk** [comment]
When could we expect getting a 6.3.x kernel in the Pop!_OS? (if everything would go fine)

**Comment by mmstick** [comment]
@pktiuk  Due to regressions in 6.3, and that they are already shifting to 6.4, a 6.4 kernel is more likely.

**Pull request closed without merging**
