### PR TITLE
ACPICA: Fix operand resolution

### PR DESCRIPTION
**Pull request by skryvets**
Addresses #161 
[Source](https://github.com/acpica/acpica/pull/745/files)

### CODE REVIEW

**Comment by 13r0ck** [comment]
Why not commit this upstream?

**Comment by skryvets** [comment]
It seems to me that "pop-os/linux" is a fork which is maintained separately:

image

If you sync with upstream, then yes, there is no need for this one. Is that the case?

**Comment by 13r0ck** [comment]
Yes we do sync with upstream. Thank you for bringing this to our attention!

**Comment by LookedPath** [comment]
This has been merged into mainline, is there any possibility of seeing it merged in here too?
Every time my XPS 15 7590 goes into S2 it's a coin flip whether it's going to wake up or not.

https://github.com/torvalds/linux/commit/7dfb216eda99bbfc2a8c3b03d2eec63314f52b3c

**Pull request closed without merging**
