### PR TITLE
Linux 5.19

### PR DESCRIPTION
**Pull request by 13r0ck**
:tada:

### CODE REVIEW

**Comment by n3m0-22** [comment]
Tested `22.04` on `oryp4` and `gaze15`

Most testing passed. After installing `5.19` both machines would always reboot into integrated graphics mode. This was fixed by the complete removal, and reinstall of the `510` or `515` driver. The `470` driver would not install on either machine. Completely removing the current nvidia driver first did not fix the issue. Booting back into the `5.18.10` kernel the `470` driver still would not install. It would however install without issue on a clean install prior to adding the new kernel. 

[22.04-oryp4-kernel-testing.txt](https://github.com/pop-os/linux/files/9271117/22.04-oryp4-kernel-testing.txt)

[22.04-gaze15-kernel-testing.txt](https://github.com/pop-os/linux/files/9271118/22.04-gaze15-kernel-testing.txt)

[nvidia-470-error.txt](https://github.com/pop-os/linux/files/9271119/nvidia-470-error.txt)

**Comment by 13r0ck** [comment]
@n3m0-22 does https://github.com/pop-os/nvidia-graphics-drivers/pull/157 help?

**Comment by n3m0-22** [comment]
Adding https://github.com/pop-os/nvidia-graphics-drivers/pull/157 did not resolve the issue. I tested by adding it before, and after installing the new kernel. I also tried running `sudo apt purge ~nnvidia && sudo apt autoremove` and rebooting after adding the `515.57` PR, but the error with still occurs when installing the `470` driver.

**Comment by gangwerz** [comment]
> Adding [pop-os/nvidia-graphics-drivers#157](https://github.com/pop-os/nvidia-graphics-drivers/pull/157) did not resolve the issue. I tested by adding it before, and after installing the new kernel. I also tried running `sudo apt purge ~nnvidia && sudo apt autoremove` and rebooting after adding the `515.57` PR, but the error with still occurs when installing the `470` driver.

Do you see any DKMS errors when installing 470 like it is failing to build against the newer kernel? Usually those need a bump from Nvidia to be cleared up

**Comment by n3m0-22** [comment]
Yes, in fact this one stands out. 

```
ERROR (dkms apport): kernel package linux-headers-5.19.0-76051900-generic is not supported
Consult /var/lib/dkms/nvidia/470.129.06/build/make.log for more information.
```

[make.log](https://github.com/pop-os/linux/files/9272735/make.log)

**Comment by gangwerz** [comment]
My Galago has finally finished testing the 150 suspend cycles. I tried switching to the Nvidia 470 driver as well, and I am seeing the DKMS build failing. 

I noticed that the minor version of 470 that is being installed is 470.129.06, while 470.141.03 is the latest release. I cannot find any posts indicating that a newer release alone clears up this block.

However, I did find a Launchpad bug thread about this - https://bugs.launchpad.net/ubuntu/+source/nvidia-graphics-drivers-470/+bug/1978539

**Comment by 13r0ck** [comment]
does https://github.com/pop-os/nvidia-graphics-drivers-470/pull/8 help?

**Comment by 13r0ck** [comment]
@pop-os/quality-assurance https://github.com/pop-os/nvidia-graphics-drivers-470/pull/8 works, so is this good to approve now?

**Comment by n3m0-22** [comment]
Re-tested `22.04` on `oryp4` and `gaze15`
All previous issues I listed listed above have been resolved by https://github.com/pop-os/nvidia-graphics-drivers-470/pull/8.

**Comment by linuxgnuru** [comment]
Tested on hp-devone, oryp9, and lemp11
[hpdev.txt](https://github.com/pop-os/linux/files/9339832/hpdev.txt)

[oryp9.txt](https://github.com/pop-os/linux/files/9339833/oryp9.txt)

[lemp11.txt](https://github.com/pop-os/linux/files/9339835/lemp11.txt)

**Review by linuxgnuru — APPROVED** [review]
Tested Thelio-Mira-b1 and Thelio-r2 with no issues

**Review by crawfxrd — APPROVED** [review]

**Comment by jackpot51** [comment]
Was virtuabox and zfs tested?

**Pull request merged**
