### PR TITLE
Linux 6.0.3

### PR DESCRIPTION
**Pull request by jackpot51**
https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.0.3

Fixes AMD GPU performance regression: https://gitlab.freedesktop.org/drm/amd/-/issues/2189

Upstream attempted a fix for the DRM issue, make sure the affected system still has plymouth working.

### CODE REVIEW

**Review by mmstick — APPROVED** [review]

**Comment by n3m0-22** [comment]
Tested with Pop!_OS 22.04 on Dev One and gaze15
Note: The patches for 6.0.2 in master are necessary 
Working:

 - [x] bcmwl-kernel-source
 - [x] virtualbox 6.1.36
   - [x] ext-pack
   - [x] guest additions
 - [x] virtualbox 7.0.0
   - [x] ext-pack
   - [x] guest additions
 - [x] ZFS
   - [x] create pool
   - [x] add/remove files and directories
   - [x] remove pool

**Comment by n3m0-22** [comment]
Testing for Pop 22.04 on each of the following machines has passed.

[6.0.3-22.04-darp6.txt](https://github.com/pop-os/linux/files/9855269/6.0.3-22.04-darp6.txt)
[6.0.3-22.04-devone.txt](https://github.com/pop-os/linux/files/9855270/6.0.3-22.04-devone.txt)
[6.0.3-22.04-gaze15.txt](https://github.com/pop-os/linux/files/9855271/6.0.3-22.04-gaze15.txt)
[6.0.3-22.04-lemp11.txt](https://github.com/pop-os/linux/files/9855272/6.0.3-22.04-lemp11.txt)
[6.0.3-22.04-oryp4.txt](https://github.com/pop-os/linux/files/9855273/6.0.3-22.04-oryp4.txt)

**Review by leviport — APPROVED** [review]
I've been running this on a few machines without issue for the last 4 or 5 days. I also did some quick checks on a few different desktops in the lab, and everything is looking good. Between these checks and @n3m0-22 's more thorough testing, I think this kernel is good to go.

**Comment by leviport** [comment]
Oh and Nvidia-DRM seems good as well, forgot to mention that. Mira-b3 with a 2080 shows Plymouth as expected, and that was a machine that was troublesome with Nvidia-DRM in the past.

**Pull request merged**
