### PR TITLE
Linux 6.2 - Focal

### PR DESCRIPTION
**Pull request by 13r0ck**
#228 but for focal

### CODE REVIEW

**Comment by XV-02** [comment]
I'm getting dkms errors trying to install the 525 driver (as part of the system76-driver-nvidia package) under Ubuntu Focal. This is not a problem under Pop 20.04.

**Comment by 13r0ck** [comment]
what errors? `apt policy nvidia-driver-525` as well please

**Comment by XV-02** [comment]
Error output from Ubuntu:
[installerrors.log](https://github.com/pop-os/linux/files/10924839/installerrors.log)

Policy under Pop: 
[policy525.log](https://github.com/pop-os/linux/files/10924841/policy525.log)

Under Ubuntu:
[policy525-2.log](https://github.com/pop-os/linux/files/10924929/policy525-2.log)

As a note: Ubuntu is trying to install Nvidia 525._60.11_ not 525._85.05_ as under Pop. 

Gathering logs for virtualbox and bcmwl-kernel-source on both Pop and Ubuntu just now.

**Comment by XV-02** [comment]
Both Ubuntu and Pop focal are having issues installing Virtualbox and bcmwl-kernel-source. Both are failing with DKMS related installation errors. 

Pop shop is spitting out:
```
Error while installing package: installed virtualbox-dkms package 
post-installation script subprocess returned error exit status 10
```
And both Ubuntu and Pop look to be having the same issues. The following were pulled from Ubuntu:
[Virtualbox_installerror.log](https://github.com/pop-os/linux/files/10925958/Virtualbox_installerror.log)
[BCMWL_installerror.log](https://github.com/pop-os/linux/files/10925959/BCMWL_installerror.log)

**Comment by n3m0-22** [comment]
After installing I am seeing a warning `The volume "efi" has on 22.1 MB disk space`. Running `df -h` shows that `/boot/efi` is only `498M`. On Jammy we bumped this up to `1020M`. This seems like something we will need to address.

**Comment by leviport** [comment]
I know it has sometimes been suggested to change initramfs compression to xz instead of zstd. It's probably slower, but I think it makes the initrd's a bit smaller.

**Comment by 13r0ck** [comment]
@XV-02 
> Both Ubuntu and Pop focal are having issues installing Virtualbox
https://github.com/pop-os/virtualbox/pull/7
https://github.com/pop-os/virtualbox-ext-pack/pull/1

> and bcmwl-kernel-source.

What version are you trying to install. We already have the most recent version released. Might just be held back from focal for some reason

**Comment by 13r0ck** [comment]
@XV-02 
> As a note: Ubuntu is trying to install Nvidia 525.60.11 not 525.85.05 as under Pop.

Does [this](As a note: Ubuntu is trying to install Nvidia 525.60.11 not 525.85.05 as under Pop.) help with that

**Comment by 13r0ck** [comment]
@XV-02 gettting virtualbox to work on focal with 6.2 is going to be an undertaking.
It might be best to close this ant put focal on the 6.1 lts kernel and call it a day. Can you mainline focal onto 6.1.14 and see what issues there might be please?

**Comment by XV-02** [comment]
> @XV-02 gettting virtualbox to work on focal with 6.2 is going to be an undertaking. It might be best to close this ant put focal on the 6.1 lts kernel and call it a day. Can you mainline focal onto 6.1.14 and see what issues there might be please?

Can do.

**Comment by XV-02** [comment]
As a note: the mainline build of 6.1.14 failed for amd64 architecture. I'm testing 6.1.15 instead, which has a successful amd64 mainline build.

**Comment by XV-02** [comment]
An additional note, I'm getting dependency errors tied to `libc6` version. It wants `>=2.35`, focal repo has `2.31`
Going through, looks like the other dependencies should all be good.

**Comment by 13r0ck** [comment]
We will either want 6.1 (LTS), or now that we merged 6.2.6, that for focal

**Comment by jackpot51** [comment]
@13r0ck want to try taking the latest master and making a PR for focal?

**Pull request closed without merging**
