### PR TITLE
21.10 Hardware Enablement

### PR DESCRIPTION
**Pull request by jackpot51**
Basically the same as https://github.com/pop-os/linux/pull/66 but building for all series. Merge by force push, then delete master_impish.

### CODE REVIEW

**Comment by jacobgkau** [comment]
It looks like this failed to build for Focal on the build server.

**Comment by leviport** [comment]
Do we need https://github.com/pop-os/linux/pull/61 sorted out before this gets merged?

**Comment by jackpot51** [comment]
@leviport any TBT issues with this? @crawfxrd what do you think?

**Comment by leviport** [comment]
It definitely seems like something's not right with TBT. I'm unable to connect to the G-Drive with darp6. This is the message I see when I attempt to authorize it.
Screenshot from 2021-09-08 16-46-43

**Comment by crawfxrd** [comment]
@leviport is that with out without the revert?

#61 is hack to force using the firmware-based TBT connection manager, since the software-based connection manager isn't working (on TGL-U, at least).

**Comment by leviport** [comment]
It's just with the `impish` branch added. If that TBT bug only applies to darp6, then I might be something unrelated. I did, however, try the G-Drive on lemp10 running Ubuntu 20.04 with this `impish` branch added, and all I got was "thunderbolt is not supported".

**Comment by jackpot51** [comment]
@leviport it would be good to test the fix-tbt kernel on 21.10. If that works I will bring it into this PR.

**Review by leviport — APPROVED** [review]

**Pull request merged**
