### PR TITLE
Linux 5.17.15

### PR DESCRIPTION
**Pull request by jackpot51**
https://cdn.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.17.15

### CODE REVIEW

**Comment by n3m0-22** [comment]
Tested `20.04`, `21.10`, and `22.04` on `orpy4`, `gaze15`, and `darp6`. All testing has passed with the exception of 150 suspend/resume cycles which is running now. Tested with both 470 drivers as well as 510 and 515 with no issues. 

Note: It was necessary to add the bluetooth suspend script to `21.10` for suspend with a bluetooth device connected to work.

[20.04-5.17.15-testing.txt](https://github.com/pop-os/linux/files/8943676/20.04-5.17.15-testing.txt)
[21.10-5.17.15-testing.txt](https://github.com/pop-os/linux/files/8943677/21.10-5.17.15-testing.txt)
[22.04-5.17.15-testing.txt](https://github.com/pop-os/linux/files/8943678/22.04-5.17.15-testing.txt)

**Comment by gangwerz** [comment]
I tested with 22.04 on the galp5. No errors, aside from Nvidia corrupting the fonts and icons (ref pop-os/nvidia-graphics-drivers#133)

[galp5-22.04-linux-5.17.15.txt](https://github.com/pop-os/linux/files/8950017/galp5-22.04-linux-5.17.15.txt)

**Comment by linuxgnuru** [comment]
No issues with galp5-uma

[22.04-5.17.15-galp5-uma-testing.txt](https://github.com/pop-os/linux/files/8950336/22.04-5.17.15-galp5-uma-testing.txt)

**Comment by jacobgkau** [comment]
lemp10 testing has passed: [5.17.15-lemp10-22.04.txt](https://github.com/pop-os/linux/files/8950627/5.17.15-lemp10-22.04.txt)

Still working on darp7.

**Comment by leviport** [comment]
We will also have to test Ubuntu with this kernel

**Comment by n3m0-22** [comment]
Ubuntu 22.04 all testing passed on gaze15. [22.04-5.17.15-testing.txt](https://github.com/pop-os/linux/files/8953189/22.04-5.17.15-testing.txt)

**Comment by leviport** [comment]
Here is a checklist to track what needs to be tested:

oryp8:
- [ ] Pop 22.04 
- [ ] Ubuntu 22.04

lemp10: 
- [ ] Pop 22.04 
- [ ] Ubuntu 22.04

darp8: 
- [ ] Pop 22.04 
- [ ] Ubuntu 22.04

galp5:
- [ ] Pop 22.04 
- [ ] Ubuntu 22.04

gaze17:
- [ ] Pop 22.04 
- [ ] Ubuntu 22.04

Dev One:
- [ ] Pop 22.04

kudu6:
- [ ] Pop 22.04 
- [ ] Ubuntu 22.04

pang11:
- [ ] Pop 22.04 
- [ ] Ubuntu 22.04

thelio-b3:
- [ ] Pop 22.04 
- [ ] Ubuntu 22.04

thelio-mira-b2:
- [ ] Pop 22.04 
- [ ] Ubuntu 22.04

thelio-mira-b3:
- [ ] Pop 22.04 
- [ ] Ubuntu 22.04

thelio-r2:
- [ ] Pop 22.04 
- [ ] Ubuntu 22.04

thelio-mira-r2:
- [ ] Pop 22.04 
- [ ] Ubuntu 22.04

thelio-major-r2:
- [ ] Pop 22.04 
- [ ] Ubuntu 22.04

thelio-mega-r1:
- [ ] Pop 22.04 
- [ ] Ubuntu 22.04

thelio-major-b3:
- [ ] Pop 22.04 
- [ ] Ubuntu 22.04

**Comment by XV-02** [comment]
Passed on Pop 22.04:

- [Gaze17](https://github.com/pop-os/linux/files/8959473/Pop22.04-Kernel5.17.15-Gaze17.txt)
- [Pang11](https://github.com/pop-os/linux/files/8959510/Pop22.04-Kernel5.17.15-Pang11.txt)
- [Galp5 UMA](https://github.com/pop-os/linux/files/8959511/Pop22.04-Kernel5.17.15-Galp5UMA.txt)

**Review by 13r0ck — APPROVED** [review]

**Review by XV-02 — CHANGES_REQUESTED** [review]
There is a regression under Ubuntu 22.04 on the Galp5-3050:

When in integrated graphics mode, the drop-down to switch graphics mode doesn't present.
This is true with our current master-packages install and without, and does not present on the currently released 5.17.5 Kernel. `system76-power graphics [insert mode here]` works as expected, however.

**Comment by jackpot51** [comment]
I have a galp5 1650 and will test this on there

**Comment by linuxgnuru** [comment]
Kudu6
- Ubuntu 22.04:
[Ubuntu22.04-Kernel-5.17.15-Kudu6.txt](https://github.com/pop-os/linux/files/8971407/Ubuntu22.04-Kernel-5.17.15-Kudu6.txt)

**Review by XV-02 — APPROVED** [review]
## Do Not Release Until Monday 27th June, 2022
Per: @leviport 

This has been tested against 
- Dev One
- Kudu6
- Gaze17
- Lemp9
- Galp5 3050
- Major R2 w/Nvidia 30xx
- Mira R2 w/Nvidia 20xx
- Mira B3 w/ Integrated and AMD

These collectively represent a cross section of major hardware components and broad coverage of hardware related Kernel regressions. On all these platforms, Kernel tests passed.

**Comment by jackpot51** [comment]
We can prevent release by simply not doing a repo-release change.

**Pull request merged**
