### PR TITLE
Add audio quirks for addw2 and gaze15

### PR DESCRIPTION
**Pull request by jackpot51**
Rebase when approved

### CODE REVIEW

**Comment by leviport** [comment]
I'm not getting the audio combo jack popup on the 15" 1650 Ti Gazelle when I plug in a headset.

**Comment by jackpot51** [comment]
@leviport on the 1650/1650 Ti that was expected as that is how the gaze14 worked on those GPUs. If headset microphone is not functional let me know and I will try something else

**Comment by leviport** [comment]
Combo jack headset mic doesn't work, but the other plug that is mic only works fine.

**Comment by jackpot51** [comment]
Thanks, I will see what I can do

**Comment by jackpot51** [comment]
Pushed a change using ALC293 fixup for all systems since they all seem to use that codec

**Pull request merged**
