### PR TITLE
Add gaze16

### PR DESCRIPTION
**Pull request by jackpot51**
Recommended by https://gitlab.freedesktop.org/drm/intel/-/issues/3662. Force push when approved to avoid rebuilding.

- [x] Fix for TGL-H kernel panics
- [x] Add gaze16 audio quirks

### CODE REVIEW

**Comment by crawfxrd** [comment]
On the 3050, headphones and mic individually work, but combo headset does not.

**Comment by jackpot51** [comment]
Yeah, looks like the quirk needs to be different. The gaze16  uses the ALC256 which was not used by the gaze15

**Comment by jackpot51** [comment]
The latest commit has the right quirk, I tested locally

**Comment by crawfxrd** [comment]
On 3050, combo headset now works, but standalone mic does not.

**Comment by jackpot51** [comment]
@crawfxrd I have the mic jack on the 3060 variant working just fine. Can you confirm that when plugging into the mic jack the input device switches to "Front Microphone"?

**Comment by crawfxrd** [comment]
Yes:

- Plug in combo headset: Switches to "Headset Microphone"
- Plug in just the mic line: Switches "Front Microphone"

Also, this strange behavior:

- Plug in mic, then headphones: Switches to "Front Microphone", but picks up input from internal mic

**Comment by jacobgkau** [comment]
Tested darp7 (21.04) and gaze14 (20.04), no regressions in display or audio.

**Review by jacobgkau — APPROVED** [review]

**Pull request merged**
