### PR TITLE
Linux 5.17.12

### PR DESCRIPTION
**Pull request by jackpot51**
https://cdn.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.17.12

Test for bluetooth suspend bug with bluez from master staging

### CODE REVIEW

**Comment by XV-02** [comment]
While 5.18.2 is being reviewed, I wanted to try and pull this down. However, despite the fact this has passed all our git checks, I'm not able to update && upgrade to this kernel with the branch specified through the usual pop-os/pop script process.

Top line: I can't get this to update from our repos as far as I can tell, nor are any errors popping out of the `apt update` output

**Comment by XV-02** [comment]
Expanding on this, when trying to pull down this branch for testing, the system attempts to install `5.15.0` kernel components. Version info has the hash fragment `3235706` appended, matching the most recent (June 3rd) commits. Notably, the indicated commit https://github.com/pop-os/linux/pull/144/commits/3235706ffacf3c2f19646742d5ad308be5e134a5 was required in order for the branch to build correctly. `5.15.0` appears to match the version for Debian's current `main` jammy-jellyfish kernel looking at launchpad.

**Comment by jackpot51** [comment]
There's a new 5.17 so I will just pull that

**Comment by jackpot51** [comment]
Obsolete, see #152

**Pull request closed without merging**
