### PR TITLE
Add quirks for Sabrent Rocket Q on darp7, galp5, lemp9, and lemp10

### PR DESCRIPTION
**Pull request by jacobgkau**
This gets the Sabrent Rocket Q 8TB drive working in the products where it was not previously working (which would quadruple the maximum storage we're able to offer in these products.) I think it would be a good idea to confirm if the 4TB drive also needs the same fixes, so it can be added to the same section.

`NVME_QUIRK_NO_DEEPEST_PS` is needed to prevent random failures while using the drive (as it enters/exits `PS4`). `NVME_QUIRK_SIMPLE_SUSPEND` is needed to prevent failure when resuming from suspend.

If we merge this here, then I'll also try to submit it upstream.

### CODE REVIEW

**Comment by jacobgkau** [comment]
It turns out the 4TB drive uses the same NVMe controller as the 8TB drive, so the PCI IDs are the same.

sabrent-pcie

I've been sitting on this because I'm still having I/O errors on the 8TB drive while running heavy benchmarks in the following configs:
- darp7 & lemp10, when stressing the 8TB drive and another drive at the same time. (Not while stressing the 8TB drive by itself.)
- galp5 with the 8TB drive in its single slot.

The I/O errors have been difficult to narrow down. They're not as consistent as the failures before applying these quirks. However, they don't happen with the same drive in other devices, or with other drives in the same devices. I've confirmed they do still happen on proprietary Clevo firmware. They're triggered by running `fio` with either a large `numjobs`, or a medium `iodepth` and a medium `numjobs`.

I think this patch would still be worth shipping, because it would prevent anyone who buys a 4TB/8TB Sabrent drive aftermarket from having to apply the `nvme_core.default_ps_max_latency_us=2000` boot option manually. We just wouldn't be able to sell the drives in these products unless we can figure out the additional errors. I'm marking this ready for review as I've gotten as far as I can from this end.

**Comment by techaround** [comment]
I have a darp7 with the 8TB Sabrent nvme using nvme_core.default_ps_max_latency_us=2000.
PopOs! 20.04
I am able to boot and do most things, but I tried playing some videos using Emby and every time I do within 5 minutes, the drive is put into read only mode. When I reboot it seems fine, but I don't think nvme_core.default_ps_max_latency_us=2000 is enough.
Sorry if this does not belong here.

**Comment by jacobgkau** [comment]
> I am able to boot and do most things, but I tried playing some videos using Emby and every time I do within 5 minutes, the drive is put into read only mode. When I reboot it seems fine, but I don't think nvme_core.default_ps_max_latency_us=2000 is enough.

Interesting, thank you for sharing your experience. I've used the 8TB drive a bit and hadn't seen it act up unless I was intentionally trying to make it act up, but this confirms that these options aren't enough to make the drive stable (which I appreciate-- I was wondering in the back of my head whether my particular 8TB drive could be defective, since the 4TB drive with the same controller had less issues.)

Just to be sure, would you be able to install this kernel version and check if the same issues are still present? You can install this kernel using these commands:

```
git clone https://github.com/pop-os/pop
./pop/scripts/apt add sabrent-rocket-q
sudo apt full-upgrade
sudo systemctl reboot
```

Once you're finished testing, if this new kernel doesn't help, you can go back to the normal kernel using these commands:

```
./pop/scripts/apt remove sabrent-rocket-q
sudo apt full-upgrade
sudo systemctl reboot
```

Do you know if adding the `nvme_core.default_ps_max_latency_us=2000` option resulted in any improvement in your case? Is the system less usable without the option than with it? I agree that it's not enough to make the drive reliable, but it does seem to be part of the equation and necessary for even attempting to use the drive.

**Comment by techaround** [comment]
Before using this **nvme_core.default_ps_max_latency_us=2000** - I could not get the drive to decrypt at all. I'd enter the password and it ask me to do it again -- forever.

When I started using nvme_core.default_ps_max_latency_us=2000, I thought it was the end to my problems -- everything seemed great - I installed programs -- even opened a VirtualBox machine.

But then it crashed after suspend -- I disabled suspend and then it started crashing playing video.

I will try the kernel and get back to you. (Thanks for such clear instructions)

**Comment by jacobgkau** [comment]
> But then it crashed after suspend -- I disabled suspend and then it started crashing playing video.

Suspend should be fixed with the kernel, at least-- that's what `NVME_QUIRK_SIMPLE_SUSPEND` does. (The boot option is equivalent to only `NVME_QUIRK_NO_DEEPEST_PS`.)

**Comment by techaround** [comment]
I am trying the new kernel now. So far so good. The video which would not play for more than 5 minutes is still playing 30 minutes later.

Can I continue to use this kernel or will it create problems?

**Comment by jacobgkau** [comment]
> I am trying the new kernel now. So far so good. The video which would not play for more than 5 minutes is still playing 30 minutes later.

Interesting. I wouldn't necessarily have expected this to improve stability over the boot option, but glad to hear it's helping.

> Can I continue to use this kernel or will it create problems?

There wouldn't be any harm in continuing to use this kernel short-term. Long-term, if the kernel receives other [updates](https://github.com/pop-os/linux/pulls) before this one is merged, then this one may become out-of-date. (If this PR is merged or closed, then you'll start getting `apt update` errors until you run the remove command in my earlier message.)

If you're willing to do a little more testing, the following information might be helpful:

- [Which slot](https://tech-docs.system76.com/models/darp7/repairs.html#replacing-an-m2nvme-ssd) is the 8TB SSD in?
- Is there a second SSD in the other slot?
- If there are two SSDs, if you perform this testing procedure:
  - Open two terminals, one in a directory on the 8TB SSD, the other in a directory on the second SSD.
  - Install fio: `sudo apt install fio`
  - Run this command in each terminal at the same time: `while true ; do sudo fio --ioengine=libaio --direct=1 --randrepeat=0 --refill_buffers --end_fsync=1 --rwmixread=70 --filename=./fio --name=fio-manual --size=1024m --bs=4k --rw=rw --iodepth=1 --numjobs=512 ; sleep 0.25 ; done`
  - Open a third terminal and watch `sudo dmesg --follow`. Does the 8TB drive encounter I/O errors (causing the filesystem to remount as read-only) within 15 minutes?

No obligation to do this, of course, but it would be great to confirm these results (or uncover if something's different.)

**Comment by techaround** [comment]
>>Interesting. I wouldn't necessarily have expected this to improve stability over the boot option (other than suspend), but glad to >>hear it's helping.
There is randomness -- also I woke up to the system in read only mode - so it's not fixed (note that suspend is completely disabled)
---------------------

I will be getting a 2TB nvme on monday and I would be happy to run your test then.

The 8TB is in Slot 2 right now. I plan to switch that when I get the 2TB since it can use the PCIe 4.0.

(Sabrent 2TB Rocket Q4 NVMe PCIe 4.0 )

**Comment by techaround** [comment]
I have not run your tests yet.

I got the new drive and installed it. I think it is ok, but acts weird with the 8TB is installed.
I had to do this (nvme_core.default_ps_max_latency_us=2000) to even see the 8TB drive.

If I don't, after the disk unencrypts, there is a 30 second delay before it boots and gparted only sees the boot drive.

Do you want me to run your test with nvme_core.default_ps_max_latency_us=2000?

Will running "nvme_core.default_ps_max_latency_us=2000" in the TB2 drive affect the performance? If so, I'll probably end up living without the 8TB drive until this get sorted out. 

Though happy to test

**Comment by jacobgkau** [comment]
> I had to do this (nvme_core.default_ps_max_latency_us=2000) to even see the 8TB drive.

Are you booting from a new OS installation on the new drive, or the same OS installation on the old drive? If it's a new installation, please add the `sabrent-rocket-q` kernel version using the same commands as before in my earlier message. Does that get rid of the weirdness without using `nvme_core.default_ps_max_latency_us=2000`?

> Do you want me to run your test with nvme_core.default_ps_max_latency_us=2000?

Yes, while the custom kernel is preferred, I'm also able to reproduce I/O errors with the kernel option, so knowing whether or not you're able to would tell me if we're seeing the same behavior or if my drive is potentially bad (it sounds like we're seeing the same behavior, since you were still seeing some instability with the custom kernel and with the option before.)

> Will running "nvme_core.default_ps_max_latency_us=2000" in the TB2 drive affect the performance?

Not performance, just power efficiency. An NVMe drive has various APST states, and each state takes a certain amount of time to enter/exit. What this option does is says: "If it would take more than 2000 microseconds to wake up from this level of power saving, then don't use it." With the Sabrent 4TB and 8TB drives in particular, this disables `PS4` (the deepest power-saving state) and leaves only `PS1` through `PS3` available.

You can view the list of states enabled with your kernel/boot options using `sudo nvme get-feature /dev/nvme# --feature-id=12 -H`, and you can see the current power state with `sudo nvme get-feature /dev/nvme# --feature-id=2 -H`.

> If so, I'll probably end up living without the 8TB drive until this get sorted out.

Just to be clear, there is no guarantee this will be sorted out. This PR was an attempt to get the drives working (by disabling standard features that the drive was not handling properly), and while it does improve behavior, it doesn't seem to be enough. This seems like an issue with the drive that may not be fixable without a firmware update for the drive from Sabrent.

**Comment by techaround** [comment]
> > I had to do this (nvme_core.default_ps_max_latency_us=2000) to even see the 8TB drive.
> 
> Are you booting from a new OS installation on the new drive, or the same OS installation on the old drive? If it's a new installation, please add the `sabrent-rocket-q` kernel version using the same commands as before in my earlier message. Does that get rid of the weirdness without using `nvme_core.default_ps_max_latency_us=2000`?

I am booting off the 2TB drive.

> > Do you want me to run your test with nvme_core.default_ps_max_latency_us=2000?
> 
> Yes, while the custom kernel is preferred, I'm also able to reproduce I/O errors with the kernel option, so knowing whether or not you're able to would tell me if we're seeing the same behavior or if my drive is potentially bad (it sounds like we're seeing the same behavior, since you were still seeing some instability with the custom kernel and with the option before.)

I will run several tests with different configurations and get back to you.

> > Will running "nvme_core.default_ps_max_latency_us=2000" in the TB2 drive affect the performance?
> 
> Not performance, just power efficiency. An NVMe drive has various APST states, and each state takes a certain amount of time to enter/exit. What this option does is says: "If it would take more than 2000 microseconds to wake up from this level of power saving, then don't use it." With the Sabrent 4TB and 8TB drives in particular, this disables `PS4` (the deepest power-saving state) and leaves only `PS1` through `PS3` available. (If anything, it's improving performance by not having to spend time entering/exiting `PS4`, but the ~2ms difference won't be noticeable.)
> 
> You can view the list of states enabled with your kernel/boot options using `sudo nvme get-feature /dev/nvme# --feature-id=12 -H`, and you can see the current power state with `sudo nvme get-feature /dev/nvme# --feature-id=2 -H`.
> 
> > If so, I'll probably end up living without the 8TB drive until this get sorted out.
> Just to be clear, there is no guarantee this will be sorted out. This PR was an attempt to get the drives working (by disabling standard features that the drive was not handling properly), and while it does improve behavior, it doesn't seem to be enough. This seems like an issue with the drive that may not be fixable without a firmware update for the drive from Sabrent.

Too bad I like this computer so much. I can sell the drive I guess -- seem very unfortunate.

**Comment by techaround** [comment]
testing
2tb in slot 2 (boot)
8tb in slot 2

Using the default 20.04 kernel with nvme_core.default_ps_max_latency_us=2000

I was able to boot and see both drives.
I ran your test as indicated -- very quickly the 8tb disk went read only.

Installed the custom kernel and rebooted.
could not see the 8TB at all.
tried booting the custom kernel with nvme_core.default_ps_max_latency_us=2000
still cannot see the 8TB drive

reinstalled the default kernel and rebooted
still cannot see the 8TB drive.

**Comment by dphurst** [comment]
Would Sabrent engineers talk to System76 and work with y'all to get the drives in a robust state? I'd sure like to have 4 or 8 TB in my galp5.
Thanks,
Dow Hurst

**Comment by jacobgkau** [comment]
> reinstalled the default kernel and rebooted
> still cannot see the 8TB drive.

It doesn't sound like the modified kernel was necessarily responsible for the lack of detection there, if it still wasn't detected after going back to the normal kernel. I've had cases where I need to reseat the SSD after a failure before it will detect again, so you might want to install the modified kernel again, power off, reseat it, and power on again.

**Comment by techaround** [comment]
I was running out of time to return the drive so I went ahead and did that --  good luck though

**Comment by jackpot51** [comment]
This is pretty out of date now

**Comment by jackpot51** [comment]
We can rebase this, and target it against the master_impish kernel, after arm64 builds are finished

**Pull request closed without merging**
