### PR TITLE
TGL-H GPIOs Workaround

### PR DESCRIPTION
**Pull request by jackpot51**
Includes #63 and #70, but provides a fallback for the gaze16 when it has older firmware with an older GPIO table. Not building for staging to avoid build server contention

### CODE REVIEW

**Comment by jackpot51** [comment]
I pushed this as oryp8_impish so it only builds on 21.10

**Comment by jackpot51** [comment]
I pushed this as oryp8_focal and oryp8_hirsute. When approved, I will make master the same commit to avoid rebuilts

**Review by crawfxrd — APPROVED** [review]

**Comment by jacobgkau** [comment]
On 930e87c, the 15" gaze16-3060 doesn't have working touchpad with firmware built from master (d8d400d).

**Review by jacobgkau — APPROVED** [review]
This gets audio working as expected on oryp8, and allows the touchpad to work on gaze16 with both currently-released firmware (`93c2809`) and firmware built from master with the `system76` branch of coreboot.

This will need to make its way into an iso before we release the next firmware update for gaze16.

**Pull request merged**
