### PR TITLE
Linux 6.6.10

### PR DESCRIPTION
**Pull request by mmstick**
Replaces #292

### CODE REVIEW

**Comment by pojunen** [comment]
If any uses Firewire, there is fix for certain problem on kernel **6.6.11**, which were mentioned to happen with certain AMD Ryzen based systems:
https://www.phoronix.com/news/AMD-Ryzen-Firefox-Linux-Fix

This patch:[ ](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=linux-6.6.y&id=d44bd49abe3defbc205f058f0f60aa65bc31f78a)

**Comment by mmstick** [comment]
@leviport Do you think it'd be worth skipping this for 6.6.11?

**Comment by leviport** [comment]
I'd rather not. We're almost done with this one, and we'd have to start over on 6.6.11.

**Review by XV-02 — APPROVED** [review]
Yeah, I'd rather not have to start over from scratch on 6.6.11 when we are happy to approve 6.6.10 for release! :grin: 

Yeah, everything has looked good for our checklist items, and I've been running this on multiple systems since the branch built in CI without a hint of issue, so I'm comfortable moving ahead with this.

**Comment by pojunen** [comment]
Is this released yet on stable repo?

**Comment by jacobgkau** [comment]
> Is this released yet on stable repo?

No, this has not been released in https://github.com/pop-os/repo-release yet. You can check what's been released by doing `sudo apt update` and then looking at the output of `apt policy linux-system76`:

```
jacob@serw13:~$ apt policy linux-system76
linux-system76:
  Installed: 6.6.6.76060606.202312111032~1702306143~22.04~d28ffec
  Candidate: 6.6.6.76060606.202312111032~1702306143~22.04~d28ffec
  Version table:
 *** 6.6.6.76060606.202312111032~1702306143~22.04~d28ffec 1001
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
        100 /var/lib/dpkg/status
```

As the master branch of this repository is currently on commit ID 24d69e2, that's what will be at the end of the version string in `apt policy` once this is released.

> Also could someone check PipeWire and WirePlumber updates:

Please don't bump requests in unrelated repositories. You opened those two issues within 10 minutes of making your comment here; all of the maintainers subscribed to this repo are also subscribed to the ones those issues are in, so linking them from over here is unnecessary. You can always join the [Pop!_OS Mattermost chat server](https://chat.pop-os.org/) if you feel you need to communicate about your requests outside of the issues themselves.

**Pull request merged**
