### PR TITLE
Added Device IDs to get the OneXPlayer Gamepad to work.

### PR DESCRIPTION
**Pull request by ruineka**
This will get the gamepad to work out of the box for people who use the OneXPlayer handheld. Tested extensively and everything works as expected including rumble.

### CODE REVIEW

**Comment by ruineka** [comment]
Commit 42634f2 was created by accident and I don't see a way to remove this from my end. The pull request should only be 
f788391 which only has one change done to the xpad.c flie adding device IDs.

**Comment by jackpot51** [comment]
You will need to submit changes like this upstream.

**Comment by ruineka** [comment]
> You will need to submit changes like this upstream.

Okay thanks, I'll look into this.

**Comment by jackpot51** [comment]
This may help: https://www.kernel.org/doc/html/v5.15/process/submitting-patches.html

**Comment by ruineka** [comment]
> This may help: https://www.kernel.org/doc/html/v5.15/process/submitting-patches.html

Thanks! I believe I did everything correctly and submitted a signed-off patch email upstream under linux-input.

**Pull request closed without merging**
