### PR TITLE
Linux 6.0.2

### PR DESCRIPTION
**Pull request by jackpot51**
Changelog: https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.0.2

### CODE REVIEW

**Review by 13r0ck — DISMISSED** [review]

**Comment by n3m0-22** [comment]
Breaks VirtualBox. Tested with versions `6.1.36` and `7.0.0`. This is the error when trying to run a VM.

Screenshot from 2022-10-17 11-49-29

Running `sudo /sbin/vboxconfig` results in the following:

```
vboxdrv.sh: Stopping VirtualBox services.
vboxdrv.sh: Starting VirtualBox services.
vboxdrv.sh: Building VirtualBox kernel modules.
vboxdrv.sh: failed: Look at /var/log/vbox-setup.log to find out what went wrong.

There were problems setting up VirtualBox.  To re-start the set-up process, run
  /sbin/vboxconfig
as root.  If your system is using EFI Secure Boot you may need to sign the
kernel modules (vboxdrv, vboxnetflt, vboxnetadp, vboxpci) before you can load
them. Please see your Linux system's documentation for more information.
```

Runing `sudo apt install --reinstall virtualbox-dkms` results in the following:

[virtualbox-errors.txt](https://github.com/pop-os/linux/files/9803494/virtualbox-errors.txt)

**Comment by n3m0-22** [comment]
Can't install `bcmwl-kernel-source`. 

[bcmwl-kernel-source_error.txt](https://github.com/pop-os/linux/files/9803614/bcmwl-kernel-source_error.txt)

**Comment by leviport** [comment]
Nvidia driver needs https://github.com/pop-os/nvidia-graphics-drivers/pull/165 for this kernel, I'm pretty sure.

**Comment by leviport** [comment]
The Nvidia desktop framebuffer bug may have returned with this update. Mira-b2 + GTX 1070 doesn't reach the Plymouth screen. Maybe https://github.com/pop-os/linux/pull/178 fell out of the rebase?

**Comment by n3m0-22** [comment]
- dkms error on `bcmwl-kernel-source`
- VirtualBox 6.1.36 is working
- Installing VirtualBox 7.0.0 works after removing version 6, running `sudo /sbin/vboxconfig`, and rebooting
- dkms error ZFS

**Comment by leviport** [comment]
Last commit fixes the framebuffer bug on Nvidia desktops.

**Comment by jackpot51** [comment]
For ZFS, please try https://github.com/pop-os/zfs-linux/pull/11

**Comment by n3m0-22** [comment]
ZFS is now working. I was able to create a pool add directories and files and then remove the pool.

**Comment by n3m0-22** [comment]
I'm still getting a dkms error installing bcmwl-kernel-source.

**Comment by n3m0-22** [comment]
Patch https://github.com/pop-os/bcmwl/pull/6 seems to have resolved the dkms error when installing `bcmwl-kernel-source`.

**Comment by jackpot51** [comment]
What is left for the dkms PRs?

**Comment by jackpot51** [comment]
If that is the case, please approve the BCMWL and ZFS PRs

**Review by leviport — APPROVED** [review]
Nvidia looks good now with the 470 and 515.65 fixes. I think this is ready to go now.

**Pull request merged**
