### PR TITLE
Linux 5.17.0

### PR DESCRIPTION
**Pull request by jackpot51**
Draft until the following can be verified:

- [ ] nvidia-driver-470
- [ ] nvidia-driver-510
- [ ] virtualbox (may need https://github.com/pop-os/virtualbox/pull/4)
- [ ] zfs-dkms (may need https://github.com/pop-os/zfs-linux/pull/5)

### CODE REVIEW

**Comment by XV-02** [comment]
What are you looking for verification regarding 470 & 510?

**Comment by jackpot51** [comment]
@XV-02 I mostly want to know that the DKMS modules compile.

**Comment by XV-02** [comment]
With the 5.17 kernel, a fully updated and upgraded Pop 21.10 appears to be defaulting to Integrated graphics on Kudu6. While both the CLI and GUI system76-power graphics switch seems to act as expected - the GUI brings up the splash notifying the graphics switch and then resolves the restart now/later prompt, while the CLI seem to process the change and advise a reboot is required to effect the change - on reboot the system is still in Integrated graphics.

Currently, I'm testing purging the drivers and reinstalling.

**Comment by XV-02** [comment]
The 470 driver will not install independently; dpkg reports nvidia-driver-470 claiming nvidia-dkms-470 as a dependency and vice-versa. 

However, the 510 driver will install correctly, and system76-power correctly behaves with 510 running.

**Comment by jackpot51** [comment]
Thanks, I will check it out.

**Comment by XV-02** [comment]
The same issue with the 470 driver is present in Pop 20.04. Again, the 510 driver successfully installs and functions in concert with system76-power.

**Comment by jackpot51** [comment]
@XV-02 can you provide the full output of `sudo apt-get install nvidia-driver-470`?

**Comment by XV-02** [comment]
[470InstallLog.txt](https://github.com/pop-os/linux/files/8336096/470InstallLog.txt)

**Comment by jackpot51** [comment]
Please grab the file `/var/lib/dkms/nvidia/470.86/build/make.log`

**Comment by XV-02** [comment]
[make.log](https://github.com/pop-os/linux/files/8336223/make.log)

**Comment by XV-02** [comment]
There are also some issues with Steam playing nice with the 5.17 Kernel. In dedicated Nvidia mode, Steam will not successfully launch from either the launcher or the terminal. Steam will launch in Hybrid and Integrated modes. When a game is launched in Hybrid mode, it will take advantage of the discrete GPU.

**Comment by XV-02** [comment]
The issues with the 470 driver persists on desktop. Additionally, Steam generated "Fatal Error: Failed to load steamui.so" when trying to do a clean install on the 510 driver.

**Comment by jackpot51** [comment]
Obsolete due to #130

**Pull request closed without merging**
