### PR TITLE
Linux 6.6.2

### PR DESCRIPTION
**Pull request by mmstick**
Currently has a compiler error without a warning. Bisecting our commits.

Needs https://github.com/pop-os/zfs-linux/pull/19

### CODE REVIEW

**Comment by leviport** [comment]
I installed this on my oryp9 and the keyboard backlight stopped working afterwards. I think this might be because of https://bugzilla.kernel.org/show_bug.cgi?id=218045

**Comment by mmstick** [comment]
Reverting the commit that's reported to be causing it.

**Comment by leviport** [comment]
Looks like that restored my keyboard backlight, however the OSD pop-up for keyboard backlight brightness level seems to have disappeared. That's a much more minor bug though, at least. I'll see if that's the case on another machine as well.

**Comment by mmstick** [comment]
Have you checked if this fixes the issue seen with the AMD/Intel system with Steam?

**Comment by leviport** [comment]
No, but I definitely should. I'll do that soon.

**Comment by leviport** [comment]
Unfortunately, the Steam + RX 7600 bug persists with this kernel.

**Comment by leviport** [comment]
The ZFS DKMS modules don't seem to work on this kernel. I saw errors when trying to install `zfs-dkms`. Fortunately, it looks like all other DKMS tests are passing (Virtualbox, Broadcom, NVIDIA, system76-dkms, system76-io-dkms and hp-vendor).

**Comment by leviport** [comment]
> Looks like that restored my keyboard backlight, however the OSD pop-up for keyboard backlight brightness level seems to have disappeared. That's a much more minor bug though, at least. I'll see if that's the case on another machine as well.

The brightness level OSD appears on the lab oryp9, so I'm willing to chalk that up to a quirk with my installation.

**Comment by leviport** [comment]
> The ZFS DKMS modules don't seem to work on this kernel. I saw errors when trying to install `zfs-dkms`. Fortunately, it looks like all other DKMS tests are passing (Virtualbox, Broadcom, NVIDIA, system76-dkms, system76-io-dkms and hp-vendor).

Oh sorry, I spoke too soon, the 470 driver's DKMS modules don't work with this kernel. The legacy NVIDIA check is in a different section so I didn't test it at the same time as the rest of the DKMS stuff. Sorry about that.

**Comment by leviport** [comment]
Also want make note (not a blocker) of https://github.com/pop-os/linux/issues/285 still persisting on this version.

**Pull request closed without merging**
