### PR TITLE
5.16.0

### PR DESCRIPTION
**Pull request by jackpot51**
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/diff/?id=v5.16&id2=v5.15&dt=2

### CODE REVIEW

**Comment by bflanagin** [comment]
On 21.10: (lemp9,gaze15, Mira-r)

- [x] Updating to new kernel works with `apt update && apt upgrade`
    - [x] No new dependencies are required for kernel update
- [x] `system76-power` still opperates as expected (across Intel/NVIDIA/switchable machines)
- [ ] Mic in
- [x] Audio out:
    - [x] Laptop's built-in speakers
    - [x] Headphones
    - [x] Display Port
    - [ ] HDMI
- [x] Video out via:
    - [x] DisplayPort
    - [ ] HDMI
- [ ] Thunderbolt docking station:
    - [ ] HDMI and DisplayPort
    - [ ] External storage device
    - [ ] Networking
- [ ] Suspend and resume:
    - [x] Switchable graphics laptops 
        - [x] In Hybrid graphics mode
        - [x] In Nvidia graphics mode
        - [x] In Integrated graphics mode
    - [x] Nvidia desktop
    - [ ] Discrete AMD desktop
    - [ ] Integrated Intel desktop
    - [ ] Integrated AMD desktop
    - [x] 150 suspend/resume cycles (`fwts s3 --s3-multiple 150`)
- [ ] Graphics drivers included in the kernel (Intel/AMD)
    - [ ] Switchable/hybrid graphics and graphics switching
- [x] Steam
    - [x] Steam installs via the Pop!_OS .deb in Pop!_Shop
    - [x] Steam launches from launcher
    - [x] Linux native game installs and runs
    - [x] Proton game installs and runs
- [ ] Virtualbox installs and works as expected

Will update when I have access to the needed hardware.

**Comment by bflanagin** [comment]
Virtualbox fails to install which is typical for new kernel series. Once the Thunderbolt docking station has been tested and mic-in 21.10 looks good to go.

**Comment by jackpot51** [comment]
> Virtualbox fails to install which is typical for new kernel series. Once the Thunderbolt docking station has been tested and mic-in 21.10 looks good to go.

VirtualBox will need to be fixed, I will work on that soon. Also, please test ZFS on 20.04

**Comment by leviport** [comment]
Looks like there might also be a problem with the 495 driver. Not a huge deal since that's not released yet, but thought it was worth sharing. I had 495 installed on my oryp6, and I installed 5.16 afterwards. After a reboot, I was stuck in Integrated mode (happens sometimes on this machine). When purging and reinstalling the 495 driver, I got this:
```
Building initial module for 5.16.0-76051600-generic
ERROR (dkms apport): kernel package linux-headers-5.16.0-76051600-generic is not supported
Error! Bad return status for module build on kernel: 5.16.0-76051600-generic (x86_64)
Consult /var/lib/dkms/nvidia/495.46/build/make.log for more information.
dpkg: error processing package nvidia-dkms-495 (--configure):
 installed nvidia-dkms-495 package post-installation script subprocess returned error exit status 10
dpkg: dependency problems prevent configuration of nvidia-driver-495:
 nvidia-driver-495 depends on nvidia-dkms-495 (>= 495.46); however:
  Package nvidia-dkms-495 is not configured yet.

dpkg: error processing package nvidia-driver-495 (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of nvidia-driver-460:
 nvidia-driver-460 depends on nvidia-driver-495; however:
  Package nvidia-driver-495 is not configured yet.

dpkg: error processing package nvidia-driver-460 (--configure):
 dependency problems - leaving unconfigured
No apport report written because the error message indicates its a followup error from a previous failure.
                                                                                                          No apport report written because the error message indicates its a followup error from a previous failure.
                                                                                                                                                                                                                    No apport report written because MaxReports is reached already
                                                             dpkg: dependency problems prevent configuration of system76-driver-nvidia:
 system76-driver-nvidia depends on nvidia-driver-460; however:
  Package nvidia-driver-460 is not configured yet.

dpkg: error processing package system76-driver-nvidia (--configure):
 dependency problems - leaving unconfigured
 ```

**Comment by jackpot51** [comment]
Superseded by #123

**Pull request closed without merging**
