### PR TITLE
Linux 5.16.11

### PR DESCRIPTION
**Pull request by jackpot51**
- May fix Rocket Lake integrated graphics issues
- May introduce Alder Lake integrated graphics support
- May break virtualbox-dkms and zfs-dkms until those are updated (see https://github.com/pop-os/zfs-linux/pull/3)

### CODE REVIEW

**Comment by XV-02** [comment]
This is successfully remedying the issue on rocket lake where attempting to boot with two displays attached to integrated graphics would hang the system. and enabled multi-monitor behaviour with alder lake without issues

I don't see anything to indicate that virtualbox-dkms is broken by this. 

While I'm waiting to test https://github.com/pop-os/zfs-linux/pull/3 , it is worth noting that it **does** prevent the current zfs-dkms module from successfully building. Next step will be to test in conjunction with https://github.com/pop-os/zfs-linux/pull/3. 

Other wise, no evidence of obvious regression was noticed.

**Comment by 13r0ck** [comment]
This also fixes the blocking alder lake issues

**Comment by XV-02** [comment]
# Kernel 5.16.11 Releases Tests Pop 21.10
Make a copy of this checklist for each OS version that the kernel will be released on (if merging into `master`, test Ubuntu LTS, Pop!\_OS LTS, and latest Pop!\_OS STS)

- [x] Updating to new kernel works with `apt update && apt upgrade`
    - [x] No new dependencies are required for kernel update
- [x] `system76-power` still opperates as expected (across Intel/NVIDIA/switchable machines)
- [x] Mic in
- [x] Audio out:
    - [x] Laptop's built-in speakers
    - [x] Headphones
    - [x] Display Port
    - [x] HDMI
- [x] Video out via:
    - [x] DisplayPort
    - [x] HDMI
- [x] Thunderbolt docking station:
    - [x] HDMI and DisplayPort
    - [x] External storage device
    - [x] Networking
- [x] Suspend and resume:
    - [x] Switchable graphics laptops 
        - [x] In Hybrid graphics mode
        - [x] In Nvidia graphics mode
        - [x] In Integrated graphics mode
    - [x] Nvidia desktop
    - [x] Discrete AMD desktop
    - [x] Integrated Intel desktop
    - [x] Integrated AMD desktop
    - [x] 150 suspend/resume cycles (`fwts s3 --s3-multiple 150`)
- [x] Graphics drivers included in the kernel (Intel/AMD)
    - [x] Switchable/hybrid graphics and graphics switching
- [x] Steam
    - [x] Steam installs via the Pop!_OS .deb in Pop!_Shop
    - [x] Steam launches from launcher
    - [x] Linux native game installs and runs
    - [x] Proton game installs and runs
- [x] Virtualbox installs and works as expected

**Comment by XV-02** [comment]
# Kernel 5.16.11 Releases Tests Pop 20.04
Make a copy of this checklist for each OS version that the kernel will be released on (if merging into `master`, test Ubuntu LTS, Pop!\_OS LTS, and latest Pop!\_OS STS)

- [x] Updating to new kernel works with `apt update && apt upgrade`
    - [x] No new dependencies are required for kernel update
- [x] `system76-power` still opperates as expected (across Intel/NVIDIA/switchable machines)
- [x] Mic in
- [x] Audio out:
    - [x] Laptop's built-in speakers
    - [x] Headphones
    - [x] Display Port
    - [x] HDMI
- [x] Video out via:
    - [x] DisplayPort
    - [x] HDMI
- [x] Thunderbolt docking station:
    - [x] HDMI and DisplayPort
    - [x] External storage device
    - [x] Networking
- [x] Suspend and resume:
    - [x] Switchable graphics laptops 
        - [x] In Hybrid graphics mode
        - [x] In Nvidia graphics mode
        - [x] In Integrated graphics mode
    - [x] Nvidia desktop
    - [x] Discrete AMD desktop
    - [x] Integrated Intel desktop
    - [x] Integrated AMD desktop
    - [x] 150 suspend/resume cycles (`fwts s3 --s3-multiple 150`)
- [x] Graphics drivers included in the kernel (Intel/AMD)
    - [x] Switchable/hybrid graphics and graphics switching
- [x] Steam
    - [x] Steam installs via the Pop!_OS .deb in Pop!_Shop
    - [x] Steam launches from launcher
    - [x] Linux native game installs and runs
    - [x] Proton game installs and runs
- [x] Virtualbox installs and works as expected

**Comment by XV-02** [comment]
# Kernel 5.16.11 Releases Tests Ubuntu 20.04
Make a copy of this checklist for each OS version that the kernel will be released on (if merging into `master`, test Ubuntu LTS, Pop!\_OS LTS, and latest Pop!\_OS STS)

- [x] Updating to new kernel works with `apt update && apt upgrade`
    - [x] No new dependencies are required for kernel update
- [x] `system76-power` still opperates as expected (across Intel/NVIDIA/switchable machines)
- [x] Mic in
- [x] Audio out:
    - [x] Laptop's built-in speakers
    - [x] Headphones
    - [x] Display Port
    - [x] HDMI
- [ ] Video out via:
    - [x] DisplayPort
    - [x] HDMI
- [x] Thunderbolt docking station:
    - [x] HDMI and DisplayPort
    - [x] External storage device
    - [x] Networking
- [ ] Suspend and resume:
    - [x] Switchable graphics laptops 
        - [x] In Hybrid graphics mode
        - [x] In Nvidia graphics mode
        - [x] In Integrated graphics mode
    - [x] Nvidia desktop
    - [x] Discrete AMD desktop
    - [x] Integrated Intel desktop
    - [x] Integrated AMD desktop
    - [x] 150 suspend/resume cycles (`fwts s3 --s3-multiple 150`)
- [x] Graphics drivers included in the kernel (Intel/AMD)
    - [x] Switchable/hybrid graphics and graphics switching
- [x] Steam
    - [x] Steam launches from launcher
    - [x] Linux native game installs and runs
    - [x] Proton game installs and runs
- [X] Virtualbox installs and works as expected

**Comment by XV-02** [comment]
Nothing on the Kernel checklist failed across Pop 20.04/21.10 nor Ubuntu 20.04, nor was their any glaring weirdness or out-of-spec behaviour.

**Review by XV-02 — APPROVED** [review]
Passed QA checklists for Kernel updates without any noticable abnormalities.

**Review by crawfxrd — APPROVED** [review]

**Pull request merged**
