### PR TITLE
Linux 6.8.2 for Jammy

### PR DESCRIPTION
**Pull request by mmstick**

### CODE REVIEW

**Review by jackpot51 — DISMISSED** [review]

**Comment by jackpot51** [comment]
Make sure to include #302

**Review by jackpot51 — APPROVED** [review]

**Comment by leviport** [comment]
This doesn't appear to fix https://github.com/pop-os/linux/issues/304, unfortunately

**Comment by XV-02** [comment]
@mmstick It looks as though some of the more recent 6.8.x series kernels (6.8.7 is what I just looked at) might have resolved the issue in https://github.com/pop-os/linux/issues/304

We might want to either shift this PR to 6.8.7, or close this and open a 6.8.7 PR (or whatever version feels appropriate)

I am seeing issues around nvidia mode-switching, but I think that's a kernel configuration issue on my end, so I'd like an engineer to work their magic to be able to test that truthfully.

**Comment by backdoorproject** [comment]
can i help with something?

**Comment by XV-02** [comment]
Given that at least one known issue was resolved by later 6.8 series kernels, I'd like to suggest closing this PR and transitioning to a 6.9.x kernel PR.

**Pull request closed without merging**
