### PR TITLE
5.15.6

### PR DESCRIPTION
**Pull request by jackpot51**
Changelog: https://cdn.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.15.6

### CODE REVIEW

**Review by 13r0ck — CHANGES_REQUESTED** [review]
Lock screen freezes after suspend on Galp5 1650ti on focal and impish. Requires hard reboot to continue.
Only in NVidia graphics

**Comment by 13r0ck** [comment]
Just to note,
I was unable to reproduce the issue on a Gaze15 1650,
But Levi was able to reproduce on a Galp5 3050, so the issue appears to be linked to the galp

**Comment by jacobgkau** [comment]
> Lock screen freezes after suspend on Galp5 1650ti on focal and impish. Requires hard reboot to continue. Only in NVidia graphics

This is also happening in 5.15.5 and is not a regression in this PR. (I'm seeing it happen on the second suspend/resume on both 5.15.5 and 5.15.6.)

**Comment by jackpot51** [comment]
Obsolete, see https://github.com/pop-os/linux/pull/100

**Pull request closed without merging**
