### PR TITLE
5.15.8

### PR DESCRIPTION
**Pull request by jackpot51**
Changelog: https://cdn.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.15.8

### CODE REVIEW

**Comment by 13r0ck** [comment]
Galp5 is still having suspend issues while in NVIDIA mode

**Comment by jackpot51** [comment]
> Galp5 is still having suspend issues while in NVIDIA mode

Are these regressions from 5.15.5?

**Comment by 13r0ck** [comment]
> Are these regressions from 5.15.5?
No not a regression from 5.15.5, Levi asked that I document that it is still broken here anyway.

**Review by 13r0ck — APPROVED** [review]
- [x] Updating to new kernel works with `apt update && apt upgrade`
    - [x] No new dependencies are required for kernel update
- [x] `system76-power` still opperates as expected (across Intel/NVIDIA/switchable machines)
- [x] Mic in
- [x] Audio out:
    - [x] Laptop's built-in speakers
    - [x] Headphones
    - [x] Display Port
    - [x] HDMI
- [x] Video out via:
    - [x] DisplayPort
    - [x] HDMI
- [x] Thunderbolt docking station:
    - [x] HDMI and DisplayPort
    - [x] External storage device
    - [x] Networking
- [x] Suspend and resume:  (Still broken on Galp5 in NVIDIA mode)
    - [x] Switchable graphics laptops 
        - [x] In Hybrid graphics mode
        - [x] In Nvidia graphics mode
        - [x] In Integrated graphics mode
    - [x] Nvidia desktop
    - [x] Discrete AMD desktop
    - [x] Integrated Intel desktop
    - [x] Integrated AMD desktop
    - [x] 150 suspend/resume cycles (`fwts s3 --s3-multiple 150`)
- [x] Kernel works in:
    - [x] Ubuntu LTS
    - [x] Pop!\_OS LTS
    - [x] Latest Pop!\_OS
- [x] Graphics drivers included in the kernel (Intel/AMD)
    - [x] Switchable/hybrid graphics and graphics switching
- [x] Steam
    - [x] Steam installs via the Pop!_OS .deb in Pop!_Shop
    - [x] Steam launches from launcher
    - [x] Linux native game installs and runs
    - [x] Proton game installs and runs
- [x] Virtualbox installs and works as expected

**Review by crawfxrd — APPROVED** [review]

**Pull request merged**
