### PR TITLE
Linux 6.4.2

### PR DESCRIPTION
**Pull request by mmstick**
Replaces #263 

Related PRs

- https://github.com/pop-os/linux-firmware/pull/35
- https://github.com/pop-os/zfs-linux/pull/17
- https://github.com/pop-os/virtualbox/pull/9
- https://github.com/pop-os/pop/pull/3071

### CODE REVIEW

**Comment by leviport** [comment]
My oryp9 also froze in Integrated graphics mode with my USB-C docking display plugged in. `dmesg` had pretty much the same output as https://github.com/pop-os/linux/pull/263#issuecomment-1623916157

**Comment by mmstick** [comment]
Also, I wonder if disabling system76-power would prevent this if it's something related to runtime power management.

**Comment by leviport** [comment]
Sounds good, I can give it a go. I suppose it could also be my install though. I could throw in a second drive and see if it happens on a fresh install

**Comment by leviport** [comment]
This bug is tricky. To summarize what I've found so far:
- This affects more than just oryp9, and more than just ADL-H laptops with switchable graphics. I've Also seen it on darp8, darp9, oryp11, and serw13.
- I tested the `linux-6.4.2-testing` branch which has our patches removed, and the bug still happens.
- I tested with `intel_idle.max_cstate=1`, but that seemed to have no effect.
- A USB-C to DP cable also had the freeze on oryp10. I will also test DP to MiniDP to see if it happens there as well.

For testing, I'm playing a video in Firefox, as well as adding a bit of load with `stress-ng -c 1 -m 2`.

**Comment by jglathe** [comment]
mm interesting. My observations with completely different hw: Have a newer NV card (RTX3060 or 3090), it is enough to scroll wrong in firefox wth a video playing, and the whole sys frezes. This is annoying. The same with a GTX1660, no issue. All on AMD m/b, B550 or X570 with R9-3900X..R9-5950X. And this since at least 6.0. I am happy on the GTX1660 box, the others not so much.

**Comment by mmstick** [comment]
Any difference if using our 535 NVIDIA driver?
https://github.com/pop-os/nvidia-graphics-drivers/pull/184

**Comment by leviport** [comment]
Ah, forgot to mention that. 535 vs 525 doesn't seem to make any difference. The darp8 & darp9 didn't even have the Nvidia driver installed.

**Comment by nerdboy4200** [comment]
One thing you might want to look at before releasing this is the possible bug related to PER_VMA_LOCK functionality - it appears to cause issues with user-land programs (crashing in bad ways) - see:

https://bugzilla.kernel.org/show_bug.cgi?id=217624

They point to a mailing list with possible patches (possibly a combo of patches plus partial combo fixes

**Comment by jackpot51** [comment]
I see a recommendation to revert 0bff0aaea03e2a3ed6bfa302155cca8a432a1829, we can try it

**Comment by jackpot51** [comment]
Here is a simplified patch: https://lore.kernel.org/all/20230703182150.2193578-1-surenb%40google.com/

**Comment by nerdboy4200** [comment]
Hunting through the email chain on lore - I see this finally showed up:

https://lore.kernel.org/all/20230706011400.2949242-1-surenb@google.com/

and I think the second patch in that set will do the proper disabling for that new feature.

**Comment by mmstick** [comment]
I wonder if it would be worth it to test the 6.3 rc kernels from https://kernel.ubuntu.com/~kernel-ppa/mainline/ to narrow the scope of when our i915 drm crash started happening with USB-C/docked displays.

**Review by jackpot51 — APPROVED** [review]

**Comment by XV-02** [comment]
When I was trying to test this a bit on Ubuntu, I was seeing issues with nvidia 525 dkms. Nvidia 535 seemed to be behaving though, and I haven't seen any issues with 525 ans 6.4.2 on Pop.

**Review by jackpot51 — APPROVED** [review]

**Comment by XV-02** [comment]
I think we may not release our virtualbox package as part of our PPA for Ubuntu, which is causing DKMS failures during install/kernel upgrade. When it was initially tested, that wasn't an issue, as the build for virtualbox was explicitly added to the list of sources to pull from.

**Comment by truebit** [comment]
I got two SSDs with the same "MAXIO MAP1602" nvme controller chipset, I found the controller would not init or only init one SSD, After I update my kernel to 6.4.3 due to [patch](https://github.com/pop-os/linux/commit/a3a9d63dcd15535e7fdf4c7c1b32bfaed762973a), the 1 or all SSDs would still not initialize with success due to dmesg
`Device not ready; aborting initialisation, CSTS=0x0`:
dmesg screenshot

After applying patch https://lore.kernel.org/lkml/20230714131333.5858-1-highenthalpyh@gmail.com/, it works. Could we add this patch in the upcoming release? 
Thanks

**Comment by ragardner** [comment]
Thanks for all your hard work on pop os,

Just to say that a lot of users are reporting problems with 7000 series amd gpus on kernel 6.4.x for example:
https://www.reddit.com/r/linux_gaming/comments/14whwac/psa_possible_issue_with_kernel_642_amd_graphics/

cheers

**Comment by mmstick** [comment]
@ragardner  That's probably https://github.com/pop-os/linux-firmware/issues/36 rather than the kernel.

**Pull request closed without merging**
