### PR TITLE
Linux 5.19.16

### PR DESCRIPTION
**Pull request by jackpot51**
https://cdn.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.19.16

### CODE REVIEW

**Review by 13r0ck — APPROVED** [review]

**Comment by leviport** [comment]
Looks like this breaks k10temp stuff on zen4

**Review by 13r0ck — DISMISSED** [review]

**Comment by leviport** [comment]
Bluetooth and wifi both look fine on Pop and Ubuntu with this kernel though, so that's good.

**Comment by n3m0-22** [comment]
Same dkms issues for `VirtualBox` and `bcmwl-kernel-source` as noted in https://github.com/pop-os/linux/pull/182.

**Comment by n3m0-22** [comment]
`VirtualBox 6.1.36` and `VirtualBox 7.0.0` are now both running. There is an error when upgrading from 6 to 7 `Conflicts with the installed package 'virtualbox-qt'`. Uninstalling VirtualBox 6 before installing VirtualBox 7 resolves gets around this without breaking VMs created in version 6. Extension and Guest Additions also upgrade to version 7 without issue. 

Also `bcmwl-kernel-source` is now installing.

**Comment by leviport** [comment]
Looks like Nvidia DKMS stuff is good with 515, 510, and 470

**Comment by XV-02** [comment]
I'm seeing an issue with bluetooth on Lemp9. Bluetooth devices are not being found, and as such cannot be connected to. The bluetooth settings panel just shows bluetooth as constantly searching. Checking lemp11 right now for a comparison

**Review by leviport — APPROVED** [review]
The k10temp commit has some issues. I'd revert that one, but otherwise this is good to go.

**Pull request closed without merging**
