### PR TITLE
Revert headers build directory

### PR DESCRIPTION
**Pull request by 13r0ck**
Some mysterious directories started to show up in user's root `/arch` for example.

This appears to be due to an upstream packaging change of `linux-libc-dev`. This reverts that.

### CODE REVIEW

**Comment by ziprasidone146939277** [comment]
I'm not sure if this is the right thread. What should we - safely - do whit this? Maybe delete? or wait next release?

Thanks,
Regards

```
/arch/:
x86

/arch/x86:
entry  include  tools

/arch/x86/entry:
syscalls

/arch/x86/entry/syscalls:

/arch/x86/include:
generated

/arch/x86/include/generated:
asm  uapi

/arch/x86/include/generated/asm:
syscalls_32.h

/arch/x86/include/generated/uapi:
asm

/arch/x86/include/generated/uapi/asm:
bpf_perf_event.h  errno.h  fcntl.h  ioctl.h  ioctls.h  ipcbuf.h  param.h  poll.h  resource.h  socket.h  sockios.h  termbits.h  termios.h  types.h  unistd_32.h  unistd_64.h  unistd_x32.h

/arch/x86/tools:
relocs  relocs_32.o  relocs_64.o  relocs_common.o
```

**Comment by 13r0ck** [comment]
@ziprasidone146939277 at this point it is best to wait for this to be released. The extra files arn't going to hurt anything, just some source code.

**Review by haiderkhalil0000 — APPROVED** [review]

**Comment by n3m0-22** [comment]
I have been unable to recreate this issue. I'm wondering if this is still necessary? If so is there a known way to reproduce it to test against?

**Comment by 13r0ck** [comment]
6.1.11 might be the kernel that was broken, this is likely not necessary anymore though

**Review by haiderkhalil0000 — APPROVED** [review]

**Pull request closed without merging**
