### PR TITLE
Adds an ALSA mapping for Gigabyte Pro WiFi Rev 2.1

### PR DESCRIPTION
**Pull request by 13r0ck**
This patch was written by Takashi Iwai, I am just
commiting it into the pop-os kernel before this
is upstreamed

Requires https://github.com/pop-os/alsa-ucm-conf/pull/1

### CODE REVIEW

**Comment by XV-02** [comment]
This resolves the issues on the rev 1.2 board, but not 1.1

**Comment by 13r0ck** [comment]
The issue in 1.1 is going to be a result of https://github.com/pop-os/alsa-ucm-conf/pull/1#issuecomment-1137959199= I know the solution. Working on it shortly

**Comment by XV-02** [comment]
For ease of tracking, this PR will be discussed in https://github.com/pop-os/alsa-ucm-conf/pull/1 as the two pulls are intimately tied and inseparable.

**Comment by leviport** [comment]
Since these maps look like they apply to all Gigabyte B450 boards, we should probably double-check this on thelio-r1 as well. If X570 chipsets also get the same mapping, it might also be good to check thelio-r2.

**Comment by XV-02** [comment]
Good catch @leviport , because it breaks audio-in on the Thelio R1...

**Review by XV-02 — APPROVED** [review]
This is now functional on all products which should be effected!

**Pull request merged**
