### PR TITLE
Linux 6.0.0 (22.04)

### PR DESCRIPTION
**Pull request by jackpot51**
This may improve Ryzen 6000/7000, and Intel DGPU.

### CODE REVIEW

**Comment by XV-02** [comment]
On a hybrid graphics (intel/nvidia) laptop, an install which previously could mode switch will only boot into integrated mode. Neither `system76-power graphics [nvidia/hybrid]` nor selecting the drop-menu option will work, though it will act like it's making the change in the background and prompt for a reboot, and will reboot successfully into a usable - though integrated - session. 

I also tested this behaviour against the 515, 510, and 470 driver releases, and each had the same results.

**Comment by 13r0ck** [comment]
@jackpot51, I can work on that if you would like

**Comment by jackpot51** [comment]
> @jackpot51, I can work on ☝️ that if you would like

Sure, it sounds like we need NVIDIA driver updates

**Comment by XV-02** [comment]
When attempting to reinstall the drivers with the kernel in place, it spits an error (`E: Sub-process /usr/bin/dpkg returned an error code (1)`) while modifying the kernel-stub. I `tee`ed the output just for records' sake.

[Nvidia_install_Linux_6.log](https://github.com/pop-os/linux/files/9749778/Nvidia_install_Linux_6.log)

**Comment by 13r0ck** [comment]
- [515.76 rebase here](https://github.com/pop-os/nvidia-graphics-drivers/pull/165)
- We are already on the newest nvidia driver version for 470.

**Comment by XV-02** [comment]
Looks like [the Nvidia 515.76 update](https://github.com/pop-os/nvidia-graphics-drivers/pull/165) resolves the `system76-power` issue, and plays nice (superficially at least) on both Kernel 6.0.0 and 5.19.0

[The patch for 470](https://github.com/pop-os/nvidia-graphics-drivers-470/pull/9) will install successfully on 6.0.0, but not 5.19.0 and will require join release with the Kernel.

I'll focus in on the 515 update right now, then move back to the 470/kernel 6.0.0 testing once that's cleared.

**Comment by leviport** [comment]
We probably need this 470 update working with 5.19 in case anyone runs into trouble with 6.0 and needs to boot oldkern...

**Comment by jackpot51** [comment]
Obsolete, see https://github.com/pop-os/linux/pull/182

**Pull request closed without merging**
