### PR TITLE
Linux 5.18.2

### PR DESCRIPTION
**Pull request by jackpot51**
https://cdn.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.18.2

Please test the following:
- [x] Bluetooth suspend: https://github.com/pop-os/default-settings/pull/140
- [ ] NVIDIA 470: https://github.com/pop-os/nvidia-graphics-drivers-470/pull/7
- [ ] NVIDIA 510
- [x] VirtualBox: https://github.com/pop-os/virtualbox/pull/5
- [ ] ZFS

### CODE REVIEW

**Comment by linuxgnuru** [comment]
lemp9 with master added still isn't suspending if a bluetooth device has been paired. Found that if a bluetooth device is off or on doesn't make any difference. If no bluetooth device is paired can suspend without any problem or if no device has been paired.

**Comment by jackpot51** [comment]
For bluetooth please see #148 where I added the two commits from #140

**Comment by n3m0-22** [comment]
All testing passed on `gaze15`, `orpy4`, and `darp6` running `22.04` with the exception of the mic in not working. It is picked up by plugging the mic into the headphone jack selecting headset (with mic) but then there is no audio out. All suspend resume tests passed with the new bluetooth fix.

[22.04_5.18.02.txt](https://github.com/pop-os/linux/files/8862239/22.04_5.18.02.txt)

**Comment by n3m0-22** [comment]
There is a dependency issue installing virtualbox on 21.10. 
Screenshot from 2022-06-08 09-22-38
[virtualbox-pop-shop.txt](https://github.com/pop-os/linux/files/8863060/virtualbox-pop-shop.txt)
[virtualbox-apt-install.txt](https://github.com/pop-os/linux/files/8863062/virtualbox-apt-install.txt)

**Comment by jackpot51** [comment]
@n3m0-22 is the same issue present on 22.04?

**Comment by jackpot51** [comment]
I will see about pulling virtualbox updates.

**Comment by n3m0-22** [comment]
Suspend on 21.10 with a bluetooth device paired works by adding the `pop-default-settings_bluetooth-suspend` script.

**Comment by jackpot51** [comment]
VirtualBox fix in https://github.com/pop-os/virtualbox/pull/5

**Comment by n3m0-22** [comment]
@jackpot51 Virtualbox was already installed on the machines I tested with 22.04 and ran fine. I just checked on a clean install with the this kernel and had no issue installing it.

**Comment by n3m0-22** [comment]
Dependency issue with the 470 driver on 22.04 and 21.10. 
[470-driver.txt](https://github.com/pop-os/linux/files/8863380/470-driver.txt)

**Comment by jackpot51** [comment]
@n3m0-22 does https://github.com/pop-os/nvidia-graphics-drivers-470/pull/7 address it?

**Comment by n3m0-22** [comment]
Yes https://github.com/pop-os/nvidia-graphics-drivers-470/pull/7 tested and working  on 21.10 and 22.04. Sorry I missed that.

**Comment by leviport** [comment]
[Dev One has passed testing with this kernel](https://github.com/pop-os/linux/files/8863955/2022-06-08-pop-2204-kernel-5.18.2-testing.txt)

**Comment by n3m0-22** [comment]
All testing for 21.10 now passing.
[21.10_5.18.02.txt](https://github.com/pop-os/linux/files/8864114/21.10_5.18.02.txt)

**Comment by n3m0-22** [comment]
All tests for 20.04 passed on orpy4, gaze15, and darp6 passed.

Note: Suspend resume with bluetooth device paired required pop-default-settings_bluetooth-suspend script.

**Comment by XV-02** [comment]
With Pop 22.04, the Galp5 3050 does not reach a user session with 5.18.2  and the 510 nvidia driver (both `510.68.02` and `510.73.05` ) This is true with or without disk encryption. 

This is not a problem with the 470 driver (either `470.103.01` or `470.129.06` )

**Comment by jackpot51** [comment]
I have a galp5 so I'll look into it.

**Comment by XV-02** [comment]
Adding another log. It should be the same as previous (largely speaking) but I wanted to make doubly sure I went through the update chain correctly.
[journalctl515log2.txt](https://github.com/pop-os/linux/files/8873099/journalctl515log2.txt)

**Comment by XV-02** [comment]
`Major R2` has passed our tests with this kernel update.

**Review by XV-02 — CHANGES_REQUESTED** [review]
### Cannot Reach Usable Session with 510 or 515 drivers on some Intel/Nvidia machines

The issue seen on the Galp5 3050 is also present on the Galp5 1650; Gaze17 3060b.
This issue was not present on either the Kudu6 (3060) , nor the Oryp7 (3070)

**Comment by XV-02** [comment]
Potentially barring one issue, `Pang11` passed certification with the 5.18.2 kernel. Although not a regression, the Pang11 doesn't wake on integrated keyboard input when suspended with the lid open. The power button (with a slightly long press of ~ half a second) will wake the machine, as will and external keyboard, or closing and reopening the lid. However, once resumed, the keyboard and track pad worked every time, and it reached the suspend state through terminal commands, the power menu, and lid closure, and woke every time.

**Comment by jackpot51** [comment]
Obsolete, see #154

**Pull request closed without merging**
