### PR TITLE
Linux 5.18.10

### PR DESCRIPTION
**Pull request by 13r0ck**
Same checklist from https://github.com/pop-os/linux/pull/157#issue-1276156783 applies here, but all of those should be done.

https://cdn.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.18.10

### CODE REVIEW

**Comment by 13r0ck** [comment]
Check if the issues from [5.18.8](https://github.com/pop-os/linux/pull/162#pullrequestreview-1030745774) are fixed first before continuing with remaining kernel QA

**Comment by gangwerz** [comment]
I performed a clean install of Pop 22.04, and upgraded to the 5.18.10 kernel, and set the graphics to Nvidia mode. The galp5-1650Ti was able to suspend multiple times with `fwts s3 --s3-multiple 10`. The system has just completed the kernel checklist on Pop 22.04. 

I am now working on Ubuntu 22.04, and will upload the checklists then.

**Comment by linuxgnuru** [comment]
- Thelio-mira-b3 no issues
- kudu6 no issues
- galp5 3050 - many issues but none were repeatable, several were present with current kernel as well.

**Comment by n3m0-22** [comment]
22.04 darp6 - all tests passed
[darp6-22.04-kernel-testing.txt](https://github.com/pop-os/linux/files/9080065/darp6-22.04-kernel-testing.txt)


22.04 gaze15 - all tests passed except for VirtualBox
[gaze15-22.04-kernel-testing.txt](https://github.com/pop-os/linux/files/9080068/gaze15-22.04-kernel-testing.txt)


22.04 lemp11 - all tests passed except for 150 suspend/resume
[22.04-lemp11-150-suspend-resume.log](https://github.com/pop-os/linux/files/9080070/22.04-lemp11-150-suspend-resume.log)
[lemp11-22.04-kernel-testing.txt](https://github.com/pop-os/linux/files/9080071/lemp11-22.04-kernel-testing.txt)

Note: VirtualBox installs on all machines, but on gaze15 if the guest OS uses GNOME e.g., (Pop, Ubuntu, Manjaro-GNOME, Fedora) gnome-shell restarts repeatedly and Firefox crashes. I assumed this was due to the NVIDIA driver version, but it happens with all driver versions and without an NVIDIA driver installed. It also happens on the Framwork Laptop with integrated graphics. The addition or removal of VirtualBox Extension Pack as well as VBoxGuestAddtitions seems to have no impact. Ubuntu 22.04 does not have this issue with a guest OS untill system76-driver is installed. Guests with KDE and Xfce do not have this issue.

Logs from Pop 22.04 guest on Pop 22.04 host:
[virtualbox-firefox.txt](https://github.com/pop-os/linux/files/9080127/virtualbox-firefox.txt)
[virtualbox-gnome-shell.txt](https://github.com/pop-os/linux/files/9080128/virtualbox-gnome-shell.txt)

**Comment by gangwerz** [comment]
Pop 22.04 was able to pass testing on the galp5-1650Ti.

However, on Ubuntu 22.04, I have not been able to get Steam to launch with Nvidia 515 or 510 (470 was working fine). After attempting to launch Steam, I consistently find a stack dump in `dmesg` starting with `kernel BUG at drivers/gpu/drm/drm_gem.c:155!` 

QA Checklists for Pop and Ubuntu 22.04
[galp5-1650ti-linux-5.18.10.txt](https://github.com/pop-os/linux/files/9085539/galp5-1650ti-linux-5.18.10.txt)

The `dmesg` output from Ubuntu 22.04 with Nvidia 515 after attempting to launch Steam
[20220711-0740-ubuntu-dmesg.log](https://github.com/pop-os/linux/files/9085531/20220711-0740-ubuntu-dmesg.log)

**Comment by gangwerz** [comment]
I have tested launching Steam on a clean install of Ubuntu 22.04 with 5.18.10 once more on the galp5-1650Ti, but with the [515.57](https://github.com/pop-os/nvidia-graphics-drivers/pull/157) release of the Nvidia driver.

I am still unable to launch Steam, and I see the same dump in `dmesg` as before.

**Comment by mmstick** [comment]
> [  273.378981] kernel BUG at drivers/gpu/drm/drm_gem.c:155!

Oof

**Comment by linuxgnuru** [comment]
I believe these were fixed in pop with the gnome-shell patch

**Comment by 13r0ck** [comment]
@linuxgnuru so is that an approval? Or what are we missing?

**Comment by linuxgnuru** [comment]
> @linuxgnuru so is that an approval? Or what are we missing?

I believe @gangwerz was working on Ubuntu without our system76-driver installed

**Comment by gangwerz** [comment]
> @gangwerz is that an approval?

It's an approval from me! if the concerns @n3m0-22 had were addressed as well, I can approve

**Comment by n3m0-22** [comment]
I'm still seeing issues with VirtualBox. This is an example from a fresh install on a `gaze15` of `Pop 22.04` for the host and `Pop 22.04` as the guest. 

The only changes made are:
 - `Enable EFI` 
 - `4 GB RAM`
 -  `4 Cores`
 
It can take a while, but Firefox will eventually crash and GNOME keeps restarting. This happens with or without `open-vm-tools-desktop` or `Guest Additions` as well as with and without `virtualbox-ext-pack`. This will happen before and after updating the host and guest. Adding `master` had no effect. I am seeing this in all graphics modes and with different NVIDIA drivers installed. This is happening on the `gaze15`, ` darp6`, `orpy4`, and Framework. 


https://user-images.githubusercontent.com/11048214/179589050-d448e7a5-b663-4527-8ff3-347efccb855b.mp4

**Comment by dmgiangi** [comment]
hi i would to beta-test linux 5.18.10 on pop. where can i read up?

**Review by leviport — APPROVED** [review]

**Review by crawfxrd — APPROVED** [review]

**Comment by RafalSkolasinski** [comment]
> Thanks for your interest! However, we did just complete testing on this update and it should be merged and released soon.

Is there a chance that this patch https://github.com/pop-os/linux/pull/165 will also be included?

**Comment by leviport** [comment]
@RafalSkolasinski Not in this one, but that's probably a patch that doesn't need to be in a version upgrade.

**Comment by leviport** [comment]
@dmgiangi it will not be replaced. If this branch doesn't exist, but the source is still on your machine, installing updates will just show you a 404 error and not be able to update. It can be removed afterwards though, and if the currently released version is the same as the version from that branch, nothing will be updated or downgraded.

**Pull request merged**
