### PR TITLE
Linux 6.0.6

### PR DESCRIPTION
**Pull request by jackpot51**
https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.0.6

Ensure that DKMS is working and framebuffer regression is not back.

### CODE REVIEW

**Comment by leviport** [comment]
The Plymouth screen on mira-b3 with a 2080 is showing up as expected, so the framebuffer bug has not returned.

**Review by mmstick — APPROVED** [review]

**Comment by mmstick** [comment]
And many people are reporting that this fixes their dummy output issue with integrated HD audio

**Comment by n3m0-22** [comment]
I was not able to recreate the sound issues, but [standard testing](https://github.com/system76/testing/blob/master/SOP/testing-procedures/kernel.md) where applicable is passing so far on all machines listed below.

- gaze15
- darp6
- oryp4
- Dev One
- thinkpad X1 carbon 3rd gen
- thinkpad w540
- framework 11th gen
- hp envy x360

I also tested ZFS without issue.

150 suspend/resume cycles with bluetooth device paired is running now. I will report back if there are any issues.

**Comment by leviport** [comment]
This kernel doesn't fix https://github.com/pop-os/linux/issues/187, but that problem isn't present in Ubuntu's mainline 6.0.6 version. This isn't a regression, but I'm wondering if this is a good opportunity to fix that bug, since two kernels of the same version are behaving differently.

Here is the version that works:
```
system76@pop-os:~$ uname -a
Linux pop-os 6.0.6-060006-generic #202210290932 SMP PREEMPT_DYNAMIC Sat Oct 29 09:37:56 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

And here is the version that doesn't (from this PR):
```
system76@pop-os:~$ uname -a
Linux pop-os 6.0.6-76060006-generic #202210290932~1667401208~22.04~d2df702 SMP PREEMPT_DYNAMIC Wed N x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by jackpot51** [comment]
Here are the changes from the Ubuntu version: https://github.com/pop-os/linux/compare/980f17970dd6f36f180114b26298b578a672ad2b...linux-6.0.6

**Comment by leviport** [comment]
Thanks, I'll do some local builds and see if I can narrow it down, since we probably won't release a kernel update on a Friday anyway. Since it's not a regression, we're probably still good for Monday release, even with the MST bug.

**Review by leviport — APPROVED** [review]
I didn't have much luck figuring out what's causing https://github.com/pop-os/linux/issues/187, so I'm approving this since https://github.com/pop-os/linux/issues/187 isn't a regression, and this contains an important sound fix. 

I'll continue to try my luck with fixing https://github.com/pop-os/linux/issues/187, but it'll have to happen separately from this PR.

**Pull request merged**
