### PR TITLE
Linux 6.0.12

### PR DESCRIPTION
**Pull request by jackpot51**
Ensure all DKMS installs correctly and that plymouth shows up as expected.

### CODE REVIEW

**Comment by 13r0ck** [comment]
Notes from 6.0.9 now apply here too

- [ ]Make sure this fixes https://github.com/system76/careteam/issues/122

- [ ] Make sure that nvidia still works with plymouth, this removed https://github.com/pop-os/linux/commit/3ee8b3ed6801778835a6d22767418bb1e33e02ba because there were upstream changes that likely fixed the issue.

**Comment by n3m0-22** [comment]
Tested on `gaze15`, `oryp4`, `darp6` `Dev One` with `Pop!_OS 22.04`

Initial testing is looking good. 

 - [x] Snaps working
 - [x] DKMS no errors
 - [x] ZFS working
 - [x] Plymouth working on `gaze15` and `orpy4` with `470`, `515`, `525`
 
 Note: Dev One tested with master for https://github.com/pop-os/amd64-microcode`
 
[6.0.12-testing-gaze15.txt](https://github.com/pop-os/linux/files/10241141/6.0.12-testing-gaze15.txt)
[6.0.12-testing-oryp4.txt](https://github.com/pop-os/linux/files/10241134/6.0.12-testing-oryp4.txt)
[6.0.12-testing-darp6.txt](https://github.com/pop-os/linux/files/10241135/6.0.12-testing-darp6.txt)
[6.0.12-testing-dev-one.txt](https://github.com/pop-os/linux/files/10241136/6.0.12-testing-dev-one.txt)

Updates with Ubuntu testing to follow.

**Comment by 13r0ck** [comment]
I should specify, plymouth works on nvidia thelios, I believe it was mira b1 that had the issue, no harm in testing on laptops too

**Comment by leviport** [comment]
Looks like this fixes the MST bug I was having trouble with! https://github.com/pop-os/linux/issues/187

**Comment by XV-02** [comment]
So far, everything has been looking good on a Galp6 (making sure 12th gen behaves)
On Desktops, I'm thinking a 13th gen unit, Major R2, and an older Intel unit. Do we still ship anything with integrated AMD graphics?

**Comment by leviport** [comment]
Mira-r3 has integrated AMD

**Comment by XV-02** [comment]
Looking through this PR so far:
- [x] AMD/Integrated AMD Laptop (Dev One)
- [ ] AMD/Nvidia Laptop (Kudu6)
- [x] Intel/Integrated Intel Laptop (Galp6/Darp8)
- [x] Intel/Nvidia Laptop (Oryp4/Gaze15)
- [ ] Intel Desktop
   - [ ] Integrated
   - [ ] Nvidia
   - [ ] AMD
- [ ] Ryzen Desktop (Mira R3)
   - [ ] Integrated
   - [ ] Nvidia
   - [ ] AMD
- [ ] Threadripper Desktop (Major R2)
   - [ ] Nvidia
   - [ ] AMD

**Comment by leviport** [comment]
Looks like Plymouth is broken again on mira-b3 with an Nvidia card :disappointed:

**Comment by 13r0ck** [comment]
Cherry-picked https://github.com/pop-os/linux/pull/194/commits/1b088b00d9f31dcecc5751e9c26007b12706f4f5 back onto this to fix that

**Comment by leviport** [comment]
Looks like that did the trick on mira-b3!

**Comment by jacobktm** [comment]
I've tested this kernel on Mira-R3, everything looks good.
While testing VirtualBox I did find that CPU virtualization is not enabled in the BIOS by default in Mira-R3.
The setting is found in the BIOS in Advanced Mode at `Tweaker->Advanced CPU Settings->SVM Mode` and change that from Disabled to Enabled. After that VirtualBox works as expected.

[thelio-mira-r3.txt](https://github.com/pop-os/linux/files/10282389/thelio-mira-r3.txt)

**Review by leviport — APPROVED** [review]

**Review by 13r0ck — APPROVED** [review]
:christmas_tree:

**Comment by 13r0ck** [comment]
Starting with 6.0.6 (which includes) this kernel, please do not delete released kernel branches!

**Pull request merged**
