### PR TITLE
Linux 5.17.5

### PR DESCRIPTION
**Pull request by jackpot51**
https://cdn.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.17.5

### CODE REVIEW

**Comment by leviport** [comment]
Suspend and resume on the kudu6 seems to be working as expected

**Comment by jackpot51** [comment]
> Suspend and resume on the kudu6 seems to be working as expected

Great! Let's continue with testing

**Comment by n3m0-22** [comment]
### Kernel Releases Tests

#### gaze15 22.04

- [x] Updating to new kernel works with `apt update && apt upgrade`
    - [x] No new dependencies are required for kernel update
- [x] `system76-power` still opperates as expected (across Intel/NVIDIA/switchable machines)
- [x] Audio out:
    - [x] Laptop's built-in speakers
    - [x] Headphones
    - [x] Display Port
    - [x] HDMI
- [x] Video out via:
    - [x] DisplayPort
    - [x] HDMI
- [x] Suspend and resume:
    - [x] Switchable graphics laptops 
        - [x] In Hybrid graphics mode
        - [x] In Nvidia graphics mode
        - [x] In Integrated graphics mode
    - [x] Nvidia desktop
    - [x] Integrated Intel desktop
    - [x] 150 suspend/resume cycles (`fwts s3 --s3-multiple 150`)
- [x] Graphics drivers included in the kernel (Intel/AMD)
    - [x] Switchable/hybrid graphics and graphics switching
- [x] Steam
    - [x] Steam installs via the Pop!_OS .deb in Pop!_Shop
    - [x] Steam launches from launcher
    - [x] Linux native game installs and runs
    - [x] Proton game installs and runs
- [x] Virtualbox installs and works as expected

#### darp6 22.04

- [x] Updating to new kernel works with `apt update && apt upgrade`
    - [x] No new dependencies are required for kernel update
- [x] `system76-power` still opperates as expected (across Intel/NVIDIA/switchable machines)
- [x] Audio out:
    - [x] Laptop's built-in speakers
    - [x] Headphones
    - [x] Display Port
    - [x] HDMI
- [x] Video out via:
    - [x] DisplayPort
    - [x] HDMI
- [x] Suspend and resume:
    - [x] In Integrated graphics mode
    - [x] Integrated Intel desktop
    - [x] 150 suspend/resume cycles (`fwts s3 --s3-multiple 150`)
- [x] Graphics drivers included in the kernel (Intel/AMD)
    - [x] Switchable/hybrid graphics and graphics switching
- [x] Steam
    - [x] Steam installs via the Pop!_OS .deb in Pop!_Shop
    - [x] Steam launches from launcher
    - [x] Linux native game installs and runs
    - [x] Proton game installs and runs
- [x] Virtualbox installs and works as expected

Testing on 21.10 and 20.04 now will report back

**Comment by n3m0-22** [comment]
#### gaze15 21.10

- [x] Updating to new kernel works with `apt update && apt upgrade`
    - [x] No new dependencies are required for kernel update
- [x] `system76-power` still opperates as expected (across Intel/NVIDIA/switchable machines)
- [x] Audio out:
    - [x] Laptop's built-in speakers
    - [x] Headphones
    - [x] Display Port
    - [x] HDMI
- [x] Video out via:
    - [x] DisplayPort
    - [x] HDMI
- [x] Suspend and resume:
    - [x] Switchable graphics laptops 
        - [x] In Hybrid graphics mode
        - [x] In Nvidia graphics mode
        - [x] In Integrated graphics mode
    - [x] Nvidia desktop
    - [x] Integrated Intel desktop
    - [x] 150 suspend/resume cycles (`fwts s3 --s3-multiple 150`)
- [x] Graphics drivers included in the kernel (Intel/AMD)
    - [x] Switchable/hybrid graphics and graphics switching
- [x] Steam
    - [x] Steam installs via the Pop!_OS .deb in Pop!_Shop
    - [x] Steam launches from launcher
    - [x] Linux native game installs and runs
    - [x] Proton game installs and runs
- [x] Virtualbox installs and works as expected

**Comment by n3m0-22** [comment]
#### darp6 20.04

- [x] Updating to new kernel works with `apt update && apt upgrade`
    - [x] No new dependencies are required for kernel update
- [x] `system76-power` still opperates as expected (across Intel/NVIDIA/switchable machines)
- [x] Audio out:
    - [x] Laptop's built-in speakers
    - [x] Headphones
    - [x] Display Port
    - [x] HDMI
- [x] Video out via:
    - [x] DisplayPort
    - [x] HDMI
- [x] Suspend and resume:
    - [x] In Integrated graphics mode
    - [x] Integrated Intel desktop
    - [x] 150 suspend/resume cycles (`fwts s3 --s3-multiple 150`)
- [x] Graphics drivers included in the kernel (Intel/AMD)
- [x] Steam
    - [x] Steam installs via the Pop!_OS .deb in Pop!_Shop
    - [x] Steam launches from launcher
    - [x] Linux native game installs and runs
    - [x] Proton game installs and runs
- [x] Virtualbox installs and works as expected


Setting sound to output through HDMI or mPD causes digital/SPDIF mode to turn on with the red light coming out of the mic input. It will not turn off unless rebooted or running `amixer -c 0 sset "IEC958",16 off`.

**Comment by leviport** [comment]
**kudu6 + Pop!\_OS 22.04**

- [x] Updating to new kernel works with `apt update && apt upgrade`
    - [x] No new dependencies are required for kernel update
- [x] `system76-power` still opperates as expected (across Intel/NVIDIA/switchable machines)
- [x] Mic in
- [x] Audio out:
    - [x] Laptop's built-in speakers
    - [x] Headphones
    - [x] Display Port
    - [x] HDMI
- [x] Video out via:
    - [x] DisplayPort
    - [x] HDMI
- [x] Thunderbolt docking station (USB-C/DisplayPort fallback, since kudu6 doesn't have Thunderbolt):
    - [x] HDMI and DisplayPort
    - [x] External storage device
    - [x] Networking
- [x] Suspend and resume:
    - [x] Switchable graphics laptops 
        - [x] In Hybrid graphics mode
        - [x] In Nvidia graphics mode
        - [x] In Integrated graphics mode
    - [x] 150 suspend/resume cycles (`fwts s3 --s3-multiple 150`)
- [x] Graphics drivers included in the kernel (Intel/AMD)
    - [x] Switchable/hybrid graphics and graphics switching
- [ ] Steam
    - [x] Steam installs via the Pop!_OS .deb in Pop!_Shop
    - [x] Steam launches from launcher
    - [x] Linux native game installs and runs
    - [x] Proton game installs and runs
- [x] Virtualbox installs and works as expected

**Comment by leviport** [comment]
Thunderbolt also works fine on oryp6 + 22.04 + 5.17.5

**Review by n3m0-22 — APPROVED** [review]
#### gaze15 20.04

- [x] Updating to new kernel works with `apt update && apt upgrade`
    - [x] No new dependencies are required for kernel update
- [x] `system76-power` still opperates as expected (across Intel/NVIDIA/switchable machines)
- [x] Audio out:
    - [x] Laptop's built-in speakers
    - [x] Headphones
    - [x] Display Port
    - [x] HDMI
- [x] Video out via:
    - [x] DisplayPort
    - [x] HDMI
- [x] Suspend and resume:
    - [x] Switchable graphics laptops 
        - [x] In Hybrid graphics mode
        - [x] In Nvidia graphics mode
        - [x] In Integrated graphics mode
    - [x] Nvidia desktop
    - [x] Integrated Intel desktop
    - [x] 150 suspend/resume cycles (`fwts s3 --s3-multiple 150`)
- [x] Graphics drivers included in the kernel (Intel/AMD)
    - [x] Switchable/hybrid graphics and graphics switching
- [x] Steam
    - [x] Steam installs via the Pop!_OS .deb in Pop!_Shop
    - [x] Steam launches from launcher
    - [x] Linux native game installs and runs
    - [x] Proton game installs and runs
- [x] Virtualbox installs and works as expected

**Review by leviport — APPROVED** [review]

**Review by crawfxrd — APPROVED** [review]

**Pull request merged**
