### PR TITLE
Linux 6.8.0 jammy

### PR DESCRIPTION
**Pull request by mmstick**

### CODE REVIEW

**Comment by leviport** [comment]
We also have to test some 512mb ESP installs. I was having issues with my ESP filling up when testing the 6.7.2 PR.

**Comment by jackpot51** [comment]
Please pick #299 and #300 into this.

**Comment by XV-02** [comment]
Looking into @laniakea64's comment, it looks like there has been some snap breakage in the 6.8 release candidates and we should be careful to do extra testing for snaps before we release this to Ubuntu to make sure that is no longer the case.

So far, I have seen no issues with flatpaks, nor reports of issues related to flatpaks in the wild, so I do not believe there is likely to be an issue for Pop.

**Comment by leviport** [comment]
I'm seeing success with DKMS modules for bcmwl drivers, virtualbox, and Nvidia 550 drivers, but there is a DKMS problem with Nvidia 470 drivers. We may need an accompanying update to those older Nvidia drivers as well.

**Comment by mmstick** [comment]
I heard that 470.239.06 may be compatible with Linux 6.8.0. I will package it.

**Review by leviport — APPROVED** [review]
With initramfs images being compressed more and the 470 driver update that fixes DKMS, I think this is ready to go. I've been running it for a while on a variety of hardware and haven't seen any issues with it.

**Pull request merged**
