### PR TITLE
5.15.1 (21.10)

### PR DESCRIPTION
**Pull request by jackpot51**
Changelog: https://cdn.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.15.1

### CODE REVIEW

**Comment by 13r0ck** [comment]
I haven't found any particular regressions from this kernel.

Though, trying to install+setup steam seems maybe a bit more broken (i.e. steam freezing) than usual, but that has been so broken for a while now that it is difficult to say for sure.

**Comment by leviport** [comment]
I'm seeing some weirdness on major-b3 with 5.15 and 5.15.1. When I install from the first 21.10 iso which has 5.13, everything works fine, but when I upgrade to either this 5.15 or the currently released version I start getting these bugs:
- Wifi stops working (bluetooth seems fine though)
- Sound doesn't work, journal logs show repeated pulseaudio timeouts and restarts
- Certain apps hang after opening, especially the system monitor
- Suspend seems broken

What other info would be helpful for me to gather?

**Comment by jackpot51** [comment]
@leviport please provide logs

**Comment by leviport** [comment]
Here's `journalctl -b 0` output: [major-b3-boot.log](https://github.com/pop-os/linux/files/7506104/major-b3-boot.log)

I tried to also grab `sudo dmesg` output, but that just hangs and never gives me anything.

**Comment by jackpot51** [comment]
Obsoleted by #79. I still expect the issues on thelio-major-b3 to still be there.

**Pull request closed without merging**
