### PR TITLE
Linux updates

### PR DESCRIPTION
**Pull request by jackpot51**
This rebases on Ubuntu's 5.11.0-14.15 kernel. Will force push to master when approved.

### CODE REVIEW

**Comment by jacobgkau** [comment]
Tested on:
- gaze15
    - [X] Audio ports
    - [X] Display outputs & configuration w/ audio
    - [X] Hotkeys
        - Airplane mode key only enables airplane mode; also happening on current kernel.
    - [X] Suspend/resume
    - [X] Graphics switching works
    - [X] Powers off
- lemp10
    - [X] Audio ports
    - [X] Display outputs & configuration w/ audio
    - [X] Hotkeys
        - Airplane mode key only enables airplane mode; also happening on current kernel.
    - [X] Suspend/resume
    - [ ] Powers off
        - https://github.com/pop-os/linux/issues/41 still applies.
- serw12
    - [X] Audio ports
    - [X] Display outputs & configuration w/ audio
    - [X] Hotkeys
    - [X] Suspend/resume
    - [X] Powers off

lemp10 wasn't any worse with a 4k@60Hz display than it was on the current kernel (just doesn't have 60Hz if it's booted with the display plugged in, but it becomes available after re-plugging.)

**Comment by jackpot51** [comment]
With https://github.com/pop-os/linux/pull/49/commits/ecb25cd0183314f9d7b729eed49bc8a153ab0b6e this should fix https://github.com/pop-os/linux/issues/41

**Comment by bflanagin** [comment]
Tested on Lemp9:
- [x] Audio ports
- [x] HDMI output with sound
- [x] Hotkeys
- [x] Suspend on Lid close
- [x] S3 suspend tests pass

Notes:
* No USB-C devices were tested due to lack of hardware

* "General stability" is still lost after installing an affected users application list without setting `intel_idle.max_cstate=4` in kernel parameters. However with this set the suspend tests fail so its only a partial fix.

**Review by jacobgkau — APPROVED** [review]
- darp7:
    - [X] Power off before suspend, plugged in or unplugged
    - [X] Power off after suspend, plugged in or unplugged
    - [X] Reboot plugged in and unplugged, then power off
- galp5:
    - [X] Power off before suspend, plugged in or unplugged
    - [X] Power off after suspend, plugged in or unplugged
    - [X] Reboot plugged in and unplugged, then power off
- lemp10:
    - [X] Power off before suspend, plugged in or unplugged
    - [X] Power off after suspend, plugged in or unplugged
    - [X] Reboot plugged in and unplugged, then power off

Looks like this does mitigate https://github.com/pop-os/linux/issues/41, although we'll want to either fix it in firmware or get that commit reverted in the upstream kernel so users of other distributions don't have such a basic issue with their hardware.

**Review by crawfxrd — APPROVED** [review]

**Pull request merged**
