### PR TITLE
Linux 5.16.19

### PR DESCRIPTION
**Pull request by jackpot51**

### CODE REVIEW

**Comment by linuxgnuru** [comment]
# Kernel 5.16.19 on Pop 21.10 kudu6
Make a copy of this checklist for each OS version that the kernel will be released on (if merging into `master`, test Ubuntu LTS, Pop!\_OS LTS, and latest Pop!\_OS STS)

- [x] Updating to new kernel works with `apt update && apt upgrade`
    - [x] No new dependencies are required for kernel update
- [x] `system76-power` still operates as expected (across Intel/NVIDIA/switchable machines)
- [x] Mic in
- [x] Audio out:
    - [x] Laptop's built-in speakers
    - [x] Headphones
    - [x] Display Port
    - [x] HDMI
- [x] Video out via:
    - [x] DisplayPort
    - [x] HDMI
- [ ] Suspend and resume:
    - [x] Switchable graphics laptops 
        - [x] In Hybrid graphics mode
        - [x] In Nvidia graphics mode
        - [x] In Integrated graphics mode
- [x] Steam
    - [x] Steam installs via the Pop!_OS .deb in Pop!_Shop
    - [x] Steam launches from launcher
    - [x] Linux native game installs and runs
    - [x] Proton game installs and runs
- [x] Virtualbox installs and works as expected

# Conclusion: 
Did not test the 150 suspend/wake because the system is kudu6 (AMD)

**Review by n3m0-22 — CHANGES_REQUESTED** [review]
# Kernel Releases Tests

- [x] Updating to new kernel works with `apt update && apt upgrade`
  - [x] No new dependencies are required for kernel update
- [x] `system76-power` still operates as expected (across Intel/NVIDIA/switchable machines)
- [x] Mic in
- [x] Audio out:
  - [x] Laptop's built-in speakers
  - [x] Headphones
  - [x] Display Port
  - [x] HDMI
- [x] Video out via:
  - [x] DisplayPort
  - [x] HDMI
- [x] Suspend and resume:
  - [x] Switchable graphics laptops
    - [x] In Hybrid graphics mode
    - [x] In Nvidia graphics mode
    - [x] In Integrated graphics mode
  - [x] Nvidia desktop
  - [x] Discrete AMD desktop
  - [x] Integrated Intel desktop
  - [x] 150 suspend/resume cycles (`fwts s3 --s3-multiple 150`)
- [x] Graphics drivers included in the kernel (Intel/AMD)
  - [x] Switchable/hybrid graphics and graphics switching
- [x] Steam
  - [x] Steam installs via the Pop!_OS .deb in Pop!_Shop
  - [x] Steam launches from launcher
  - [x] Linux native game installs and runs
  - [x] Proton game installs and runs
- [x] Virtualbox installs and works as expected

## Issues

- No Display Port output in any graphics mode on `22.04` on `gaze15` with `nvidia-510.60.02` but it works fine with `nvidia-470.86`

- This is still an issue <https://github.com/pop-os/nvidia-graphics-drivers/issues/133>

## Still needs to be tested

- [ ] Integrated AMD desktop
- [ ] Graphics drivers included in the kernel (Intel/AMD) *for AMD*
- [ ] All Thunderbolt docking station tests

**Comment by leviport** [comment]
Integrated AMD graphics are looking good on Jammy. I'm going to test a bit with Thunderbolt docks, but this is close to ready.

**Comment by leviport** [comment]
Thunderbolt docking station also looks good, both on a Thunderbolt laptop, and a laptop that falls back to USB/DP for docking functionality.

**Review by leviport — APPROVED** [review]

**Comment by n3m0-22** [comment]
Display port output on `gaze15` with the `510.60.02` driver is now working after installing `pop-os_22.04_amd64_nvidia_debug_70.iso`

**Pull request merged**
