### PR TITLE
Linux 5.18.2 bluetooth fixes

### PR DESCRIPTION
**Pull request by jackpot51**
This is to test the two bluetooth suspend patches. I will only build this on 22.04. If it works, I will update #147 to match.

### CODE REVIEW

**Comment by n3m0-22** [comment]
Tested the same as https://github.com/pop-os/linux/pull/147#issuecomment-1147739097. There were no changes. Suspend with a bluetooth device paired still not working.

**Comment by jackpot51** [comment]
@n3m0-22 was it tested with bluez from master staging?

**Comment by n3m0-22** [comment]
Yes it was.

**Comment by n3m0-22** [comment]
@jackpot51 I double checked by doing a clean install of 22.04 and adding bluez from master staging tested again. I have the same results of not being able to suspend with a bluetooth device paired. I can suspend with bluetooth on and nothing paired. I'm including the logs from the orpy4 and the gaze15 with suspend failures and a working suspend with bluetooth enabled and nothing paired. Hopefully that will be a bit more useful. 

[gaze15_bluetooh_suspend.txt](https://github.com/pop-os/linux/files/8853281/gaze15_bluetooh_suspend.txt)
[orpy4_bluetooth_suspend.txt](https://github.com/pop-os/linux/files/8853282/orpy4_bluetooth_suspend.txt)

**Pull request closed without merging**
