### PR TITLE
ALSA: hda - Improv 3.5mm hotplug on ROG strix B550

### PR DESCRIPTION
**Pull request by 13r0ck**
When plugging of unplugging an audio jack on this motherbaord,
sometimes the audio jacks would stop appearing to
pipewire/pulseaudio. Interestingly `cat`-ing out the file
`/proc/asound/<card number>/codec#0`, and or restarting pipewire
fixes the issue temporarily.

This PR improves the current functionality by making hotplug with
one 3.5mm jack work, it still breaks if hotplug is between multiple
jacks though.
@pop-os/quality-assurance please check with Eva+Tony if this is
good enough for now to ship while I look into possible better solutions.

### CODE REVIEW

**Comment by ids1024** [comment]
So by removing `AZX_DCAPS_PM_RUNTIME`, this would just cause some (fairly small) increase in power consumption, by not suspending the audio controller when not in use? That seems reasonable enough, though it applies to various systems that may not have any issue. I think only desktop systems, right?

**Comment by 13r0ck** [comment]
Good point. I modified the commit to only effect systems with the pci id. With that change I believe that this will only effect one other desktop system, that is what the original commit and linked issue appear to suggest https://github.com/pop-os/linux/commit/de768ce45466f3009809719eb7b1f6f5277d9373

**Review by bflanagin — COMMENTED** [review]
This is a definite improvement. Line out now works as expected. However, if you have a mic plugged in to mic in, and for some reason you toggle (unplug / plug in) line out the mic stops working until it has been toggled as well.

This isn't the expected behavior, but I don't know if it is a blocker or not.

**Comment by 13r0ck** [comment]
Force pushing for the release of 5.19 broke this PR, this is superseded by #171

**Pull request closed without merging**
