### PR TITLE
Linux 6.4.0

### PR DESCRIPTION
**Pull request by mmstick**
Replaces #262

### CODE REVIEW

**Comment by mmstick** [comment]
Haven't yet found a solution for this compiler error:

```
In file included from ./arch/x86/include/asm/linkage.h:6,
                 from ./include/linux/linkage.h:8,
                 from ./include/linux/printk.h:8,
                 from ./include/asm-generic/bug.h:22,
                 from ./arch/x86/include/asm/bug.h:87,
                 from ./include/linux/bug.h:5,
                 from ./include/linux/page-flags.h:10,
                 from kernel/bounds.c:10:
./arch/x86/include/asm/ibt.h:77:1: error: ‘nocf_check’ attribute ignored. Use ‘-fcf-protection’ option to enable it [-Werror=attributes]
   77 | extern __noendbr u64 ibt_save(bool disable);
      | ^~~~~~
./arch/x86/include/asm/ibt.h:78:1: error: ‘nocf_check’ attribute ignored. Use ‘-fcf-protection’ option to enable it [-Werror=attributes]
   78 | extern __noendbr void ibt_restore(u64 save);
      | ^~~~~~
cc1: all warnings being treated as errors
make[2]: *** [scripts/Makefile.build:114: kernel/bounds.s] Error 1
```

I've been looking through the diff between our 6.3.7 packaging and the Ubuntu mainline kernel packaging for 6.4.0 in Meld, with little luck so far.

**Comment by jglathe** [comment]
I have this since all of 6.3. I found a way to hack it out of existence (undefine it). Seems to work fine here. And yes, I had to apply it on this branch, too.

```
From 2edfc99b478339d5b1593d3b5924d0cb950861ee Mon Sep 17 00:00:00 2001
From: Jens Glathe <jens.glathe@oldschoolsolutions.biz>
Date: Sat, 18 Mar 2023 08:11:37 +0000
Subject: [PATCH] hotfix remove nocf_check attribute for ibt

Signed-off-by: Jens Glathe <jens.glathe@oldschoolsolutions.biz>
---
 arch/x86/include/asm/ibt.h | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/arch/x86/include/asm/ibt.h b/arch/x86/include/asm/ibt.h
index baae6b4fea23..f242c1fedd68 100644
--- a/arch/x86/include/asm/ibt.h
+++ b/arch/x86/include/asm/ibt.h
@@ -29,7 +29,7 @@
 #define ASM_ENDBR	"endbr32\n\t"
 #endif
 
-#define __noendbr	__attribute__((nocf_check))
+#define __noendbr
 
 /*
  * Create a dummy function pointer reference to prevent objtool from marking
-- 
2.37.2


```
[0001-hotfix-remove-nocf_check-attribute-for-ibt.patch](https://github.com/pop-os/linux/files/11919758/0001-hotfix-remove-nocf_check-attribute-for-ibt.patch)

**Comment by XV-02** [comment]
Looks like Virtualbox and our ZFS packaging will need updating to work with 6.4.0.
Nvidia (both 525 and 535), System76, and HP related DKMS seems fine.

**Comment by mmstick** [comment]
Virtualbox and ZFS packages may be fixed by these PRs

- https://github.com/pop-os/kbuild/pull/1
- https://github.com/pop-os/virtualbox/pull/9
- https://github.com/pop-os/zfs-linux/pull/17

Which can be tested with the `zfs` and `virtualbox` staging branches.

**Comment by XV-02** [comment]
Given that 6.4.1 contains fixes for a now [known security vulnerability](https://www.openwall.com/lists/oss-security/2023/07/05/1), and that this PR is undergoing testing still, should we push to 6.4.1?

**Comment by mmstick** [comment]
Yes, we should

**Comment by mmstick** [comment]
Seems even our 6.2.6 kernel is affected.

**Comment by XV-02** [comment]
There isn't, as far as I can tell, a 6.2 kernel we can move to in the interim. With 6.3's instability and its nouveau driver regressions (which is a problem with our large Nvidia user base) I think our best move is going to be trying to get 6.4.x to play nice.

**Comment by leviport** [comment]
I'm seeing the same freezing bug on my oryp9 that I saw on the 6.3.x kernels we've tested: https://github.com/pop-os/linux/pull/251#issuecomment-1523732347

I've narrowed it down to either my USB-C docking monitor that I use at the office (at home I use only the built-in display), or my bluetooth headphones that I use at the office.

I've been able to recover from this state by disconnecting my bluetooth headphones and/or switching to TTY3 and back to TTY2 (not sure which solved it, but I did both and it came back). This time I had `dmesg -w` running. Before it froze, I was seeing some of this:
```
[  479.610045] i915 0000:00:02.0: [drm] *ERROR* Atomic update failure on pipe B (start=66554 end=66555) time 214 us, min 1415, max 1439, scanline start 1410, end 1461
[  650.738328] i915 0000:00:02.0: [drm] *ERROR* Atomic update failure on pipe B (start=94764 end=94765) time 209 us, min 1415, max 1439, scanline start 1403, end 1453
[  838.949095] i915 0000:00:02.0: [drm] *ERROR* Atomic update failure on pipe B (start=125790 end=125791) time 188 us, min 1415, max 1439, scanline start 1400, end 1445
[ 1000.583743] i915 0000:00:02.0: [drm] *ERROR* Atomic update failure on pipe B (start=152435 end=152436) time 149 us, min 1415, max 1439, scanline start 1410, end 1445
[ 1694.881533] input: ATH-M50xBT2 (AVRCP) as /devices/virtual/input/input43
[ 1880.848113] i915 0000:00:02.0: [drm] *ERROR* Atomic update failure on pipe B (start=297544 end=297545) time 210 us, min 1415, max 1439, scanline start 1401, end 1452
[ 1902.819988] i915 0000:00:02.0: [drm] *ERROR* Atomic update failure on pipe B (start=301166 end=301167) time 212 us, min 1415, max 1439, scanline start 1400, end 1450
```
(you can see where I connected my bluetooth headset there as well)

and after the freeze, I saw all of this:
```
[ 2100.735563] i915 0000:00:02.0: [drm] *ERROR* [CRTC:131:pipe B] flip_done timed out
[ 2110.975701] i915 0000:00:02.0: [drm] *ERROR* flip_done timed out
[ 2110.975728] i915 0000:00:02.0: [drm] *ERROR* [CRTC:131:pipe B] commit wait timed out
[ 2121.215683] i915 0000:00:02.0: [drm] *ERROR* flip_done timed out
[ 2121.215705] i915 0000:00:02.0: [drm] *ERROR* [PLANE:82:plane 1B] commit wait timed out
[ 2131.455804] i915 0000:00:02.0: [drm] *ERROR* [CRTC:131:pipe B] flip_done timed out
[ 2141.695813] i915 0000:00:02.0: [drm] *ERROR* flip_done timed out
[ 2141.695825] i915 0000:00:02.0: [drm] *ERROR* [CRTC:131:pipe B] commit wait timed out
[ 2141.777020] rfkill: input handler enabled
[ 2151.936045] i915 0000:00:02.0: [drm] *ERROR* flip_done timed out
[ 2151.936060] i915 0000:00:02.0: [drm] *ERROR* [CONNECTOR:245:DP-1] commit wait timed out
[ 2152.039982] ------------[ cut here ]------------
[ 2152.039989] i915 0000:00:02.0: vblank wait timed out on crtc 1
[ 2152.040161] WARNING: CPU: 4 PID: 4203 at drivers/gpu/drm/drm_vblank.c:1310 drm_wait_one_vblank+0x1ef/0x210 [drm]
[ 2152.040379] Modules linked in: tls nf_conntrack_netlink xfrm_user xfrm_algo xt_addrtype br_netfilter ccm rfcomm xt_CHECKSUM xt_MASQUERADE xt_conntrack ipt_REJECT nf_reject_ipv4 xt_tcpudp nft_compat nft_chain_nat nf_nat nf_conntrack snd_seq_dummy snd_hrtimer nf_defrag_ipv6 nf_defrag_ipv4 cmac algif_hash algif_skcipher af_alg nf_tables nfnetlink zstd nvidia_uvm(POE) bridge stp llc overlay bnep zram snd_sof_pci_intel_tgl snd_sof_intel_hda_common soundwire_intel soundwire_generic_allocation soundwire_cadence snd_sof_intel_hda_mlink snd_sof_intel_hda snd_sof_pci intel_rapl_msr snd_sof_xtensa_dsp intel_rapl_common snd_sof snd_sof_utils snd_soc_hdac_hda snd_hda_ext_core snd_soc_acpi_intel_match snd_soc_acpi intel_uncore_frequency soundwire_bus intel_uncore_frequency_common intel_tcc_cooling iwlmvm snd_soc_core snd_hda_codec_realtek snd_compress snd_hda_codec_generic nvidia_drm(POE) x86_pkg_temp_thermal intel_powerclamp nvidia_modeset(POE) ledtrig_audio snd_hda_codec_hdmi ac97_bus snd_pcm_dmaengine mac80211 snd_hda_intel
[ 2152.040520]  snd_intel_dspcfg snd_intel_sdw_acpi snd_hda_codec libarc4 uvcvideo snd_hda_core snd_hwdep videobuf2_vmalloc uvc videobuf2_memops videobuf2_v4l2 snd_pcm btusb coretemp btrtl videodev btbcm snd_seq_midi snd_seq_midi_event btintel videobuf2_common snd_rawmidi btmtk nls_iso8859_1 iwlwifi kvm_intel nvidia(POE) joydev mc snd_seq cmdlinepart bluetooth kvm pmt_telemetry ecdh_generic ecc pmt_class input_leds snd_seq_device spi_nor rapl cfg80211 snd_timer hid_multitouch ee1004 mtd serio_raw snd bfq intel_cstate intel_vsec soundcore igen6_edac intel_pmc_mux typec intel_scu_pltdrv intel_hid mac_hid sparse_keymap sch_fq_codel kyber_iosched msr parport_pc ppdev lp parport ramoops pstore_blk reed_solomon pstore_zone efi_pstore ip_tables x_tables autofs4 dm_crypt hid_logitech_hidpp hid_logitech_dj usbhid raid10 raid456 async_raid6_recov async_memcpy async_pq async_xor async_tx xor raid6_pq libcrc32c raid1 raid0 multipath linear system76_io(OE) i915 drm_buddy i2c_algo_bit ttm drm_display_helper cec rc_core
[ 2152.040691]  crct10dif_pclmul drm_kms_helper crc32_pclmul polyval_clmulni polyval_generic syscopyarea ghash_clmulni_intel sysfillrect sha512_ssse3 aesni_intel hid_generic sysimgblt nvme crypto_simd cryptd thunderbolt drm sdhci_pci nvme_core r8169 spi_intel_pci i2c_i801 cqhci spi_intel i2c_smbus intel_lpss_pci realtek xhci_pci sdhci intel_lpss i2c_hid_acpi xhci_pci_renesas idma64 nvme_common i2c_hid hid video wmi pinctrl_tigerlake system76_acpi(OE)
[ 2152.040766] CPU: 4 PID: 4203 Comm: Xorg Tainted: P        W  OE      6.4.0-76060400-generic #202306271339~1688382054~22.04~b23d286
[ 2152.040778] Hardware name: System76 Oryx Pro/Oryx Pro, BIOS 2023-06-08_36c78ea 06/08/2023
[ 2152.040782] RIP: 0010:drm_wait_one_vblank+0x1ef/0x210 [drm]
[ 2152.040955] Code: fe ff ff 48 8b 7b 08 4c 8b 6f 50 4d 85 ed 74 26 e8 56 1b 15 fb 44 89 e1 4c 89 ea 48 c7 c7 40 08 5e c0 48 89 c6 e8 e1 0b 77 fa <0f> 0b e9 7b fe ff ff 48 8b 1f eb 94 4c 8b 2f eb d5 e8 6b 2f 76 fb
[ 2152.040964] RSP: 0018:ffffab7dc5ffb5b0 EFLAGS: 00010246
[ 2152.040972] RAX: 0000000000000000 RBX: ffff91dbe6568000 RCX: 0000000000000000
[ 2152.040978] RDX: 0000000000000000 RSI: 0000000000000000 RDI: 0000000000000000
[ 2152.040981] RBP: ffffab7dc5ffb608 R08: 0000000000000000 R09: 0000000000000000
[ 2152.040985] R10: 0000000000000000 R11: 0000000000000000 R12: 0000000000000001
[ 2152.040988] R13: ffff91dbc2e33320 R14: 000000000004d106 R15: ffff91dbe6553960
[ 2152.040993] FS:  00007f4e55c2ba80(0000) GS:ffff91eb3d300000(0000) knlGS:0000000000000000
[ 2152.041000] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[ 2152.041005] CR2: 00000562786a1000 CR3: 0000000182a4e000 CR4: 0000000000750ee0
[ 2152.041012] PKRU: 55555554
[ 2152.041015] Call Trace:
[ 2152.041020]  <TASK>
[ 2152.041028]  ? show_regs+0x6d/0x80
[ 2152.041046]  ? __warn+0x89/0x160
[ 2152.041060]  ? drm_wait_one_vblank+0x1ef/0x210 [drm]
[ 2152.041225]  ? report_bug+0x17e/0x1b0
[ 2152.041239]  ? handle_bug+0x46/0x90
[ 2152.041257]  ? exc_invalid_op+0x18/0x80
[ 2152.041271]  ? asm_exc_invalid_op+0x1b/0x20
[ 2152.041290]  ? drm_wait_one_vblank+0x1ef/0x210 [drm]
[ 2152.041448]  ? __pfx_autoremove_wake_function+0x10/0x10
[ 2152.041470]  drm_crtc_wait_one_vblank+0x17/0x30 [drm]
[ 2152.041623]  intel_crtc_wait_for_next_vblank+0xe/0x20 [i915]
[ 2152.042303]  hsw_audio_codec_disable+0xef/0x160 [i915]
[ 2152.042885]  intel_audio_codec_disable+0xb6/0x1d0 [i915]
[ 2152.043386]  intel_disable_ddi+0x101/0x1c0 [i915]
[ 2152.043875]  intel_encoders_disable+0x9b/0xd0 [i915]
[ 2152.044519]  hsw_crtc_disable+0x167/0x180 [i915]
[ 2152.045092]  intel_old_crtc_state_disables.constprop.0+0x38/0xa0 [i915]
[ 2152.045552]  intel_commit_modeset_disables+0x2a5/0x350 [i915]
[ 2152.045869]  ? intel_modeset_get_crtc_power_domains+0x8c/0xf0 [i915]
[ 2152.045943]  intel_atomic_commit_tail+0x190/0x920 [i915]
[ 2152.046015]  intel_atomic_commit+0x3bc/0x410 [i915]
[ 2152.046082]  drm_atomic_commit+0x96/0xd0 [drm]
[ 2152.046096]  ? __pfx___drm_printfn_info+0x10/0x10 [drm]
[ 2152.046115]  drm_client_modeset_commit_atomic+0x203/0x240 [drm]
[ 2152.046132]  drm_client_modeset_commit_locked+0x5b/0x170 [drm]
[ 2152.046147]  ? ttwu_queue_wakelist+0x135/0x1c0
[ 2152.046149]  __drm_fb_helper_restore_fbdev_mode_unlocked+0x86/0x100 [drm_kms_helper]
[ 2152.046160]  drm_fb_helper_set_par+0x2f/0x50 [drm_kms_helper]
[ 2152.046168]  intel_fbdev_set_par+0x1a/0x70 [i915]
[ 2152.046233]  fb_set_var+0x20a/0x460
[ 2152.046236]  ? set_next_entity+0xef/0x180
[ 2152.046237]  ? psi_group_change+0x219/0x530
[ 2152.046238]  ? pick_next_task_fair+0x395/0x5f0
[ 2152.046240]  fbcon_blank+0x24d/0x380
[ 2152.046242]  do_unblank_screen+0xc0/0x1c0
[ 2152.046244]  complete_change_console+0x67/0x150
[ 2152.046246]  vt_ioctl+0x484/0x9e0
[ 2152.046247]  tty_ioctl+0x2b8/0x8e0
[ 2152.046249]  ? do_syscall_64+0x67/0x90
[ 2152.046250]  ? syscall_exit_to_user_mode+0x29/0x50
[ 2152.046251]  ? do_syscall_64+0x67/0x90
[ 2152.046253]  ? __fget_light+0xa5/0x120
[ 2152.046254]  __x64_sys_ioctl+0x9d/0xe0
[ 2152.046256]  do_syscall_64+0x58/0x90
[ 2152.046258]  entry_SYSCALL_64_after_hwframe+0x72/0xdc
[ 2152.046259] RIP: 0033:0x7f4e55b1aaff
[ 2152.046262] Code: 00 48 89 44 24 18 31 c0 48 8d 44 24 60 c7 04 24 10 00 00 00 48 89 44 24 08 48 8d 44 24 20 48 89 44 24 10 b8 10 00 00 00 0f 05 <41> 89 c0 3d 00 f0 ff ff 77 1f 48 8b 44 24 18 64 48 2b 04 25 28 00
[ 2152.046262] RSP: 002b:00007ffe93fb5390 EFLAGS: 00000246 ORIG_RAX: 0000000000000010
[ 2152.046263] RAX: ffffffffffffffda RBX: 0000000000000001 RCX: 00007f4e55b1aaff
[ 2152.046264] RDX: 0000000000000001 RSI: 0000000000005605 RDI: 000000000000000e
[ 2152.046264] RBP: 000056540ba2c898 R08: 0000000000000002 R09: 00007ffe93fb51e0
[ 2152.046265] R10: 0000000000000000 R11: 0000000000000246 R12: 000056540ba2c940
[ 2152.046265] R13: 000056540ba2c894 R14: 000056540ba2c950 R15: 000056540ba2c948
[ 2152.046266]  </TASK>
[ 2152.046266] ---[ end trace 0000000000000000 ]---
[ 2152.147935] ------------[ cut here ]------------
[ 2152.147939] i915 0000:00:02.0: vblank wait timed out on crtc 1
[ 2152.148043] WARNING: CPU: 4 PID: 4203 at drivers/gpu/drm/drm_vblank.c:1310 drm_wait_one_vblank+0x1ef/0x210 [drm]
[ 2152.148157] Modules linked in: tls nf_conntrack_netlink xfrm_user xfrm_algo xt_addrtype br_netfilter ccm rfcomm xt_CHECKSUM xt_MASQUERADE xt_conntrack ipt_REJECT nf_reject_ipv4 xt_tcpudp nft_compat nft_chain_nat nf_nat nf_conntrack snd_seq_dummy snd_hrtimer nf_defrag_ipv6 nf_defrag_ipv4 cmac algif_hash algif_skcipher af_alg nf_tables nfnetlink zstd nvidia_uvm(POE) bridge stp llc overlay bnep zram snd_sof_pci_intel_tgl snd_sof_intel_hda_common soundwire_intel soundwire_generic_allocation soundwire_cadence snd_sof_intel_hda_mlink snd_sof_intel_hda snd_sof_pci intel_rapl_msr snd_sof_xtensa_dsp intel_rapl_common snd_sof snd_sof_utils snd_soc_hdac_hda snd_hda_ext_core snd_soc_acpi_intel_match snd_soc_acpi intel_uncore_frequency soundwire_bus intel_uncore_frequency_common intel_tcc_cooling iwlmvm snd_soc_core snd_hda_codec_realtek snd_compress snd_hda_codec_generic nvidia_drm(POE) x86_pkg_temp_thermal intel_powerclamp nvidia_modeset(POE) ledtrig_audio snd_hda_codec_hdmi ac97_bus snd_pcm_dmaengine mac80211 snd_hda_intel
[ 2152.148233]  snd_intel_dspcfg snd_intel_sdw_acpi snd_hda_codec libarc4 uvcvideo snd_hda_core snd_hwdep videobuf2_vmalloc uvc videobuf2_memops videobuf2_v4l2 snd_pcm btusb coretemp btrtl videodev btbcm snd_seq_midi snd_seq_midi_event btintel videobuf2_common snd_rawmidi btmtk nls_iso8859_1 iwlwifi kvm_intel nvidia(POE) joydev mc snd_seq cmdlinepart bluetooth kvm pmt_telemetry ecdh_generic ecc pmt_class input_leds snd_seq_device spi_nor rapl cfg80211 snd_timer hid_multitouch ee1004 mtd serio_raw snd bfq intel_cstate intel_vsec soundcore igen6_edac intel_pmc_mux typec intel_scu_pltdrv intel_hid mac_hid sparse_keymap sch_fq_codel kyber_iosched msr parport_pc ppdev lp parport ramoops pstore_blk reed_solomon pstore_zone efi_pstore ip_tables x_tables autofs4 dm_crypt hid_logitech_hidpp hid_logitech_dj usbhid raid10 raid456 async_raid6_recov async_memcpy async_pq async_xor async_tx xor raid6_pq libcrc32c raid1 raid0 multipath linear system76_io(OE) i915 drm_buddy i2c_algo_bit ttm drm_display_helper cec rc_core
[ 2152.148323]  crct10dif_pclmul drm_kms_helper crc32_pclmul polyval_clmulni polyval_generic syscopyarea ghash_clmulni_intel sysfillrect sha512_ssse3 aesni_intel hid_generic sysimgblt nvme crypto_simd cryptd thunderbolt drm sdhci_pci nvme_core r8169 spi_intel_pci i2c_i801 cqhci spi_intel i2c_smbus intel_lpss_pci realtek xhci_pci sdhci intel_lpss i2c_hid_acpi xhci_pci_renesas idma64 nvme_common i2c_hid hid video wmi pinctrl_tigerlake system76_acpi(OE)
[ 2152.148363] CPU: 4 PID: 4203 Comm: Xorg Tainted: P        W  OE      6.4.0-76060400-generic #202306271339~1688382054~22.04~b23d286
[ 2152.148369] Hardware name: System76 Oryx Pro/Oryx Pro, BIOS 2023-06-08_36c78ea 06/08/2023
[ 2152.148371] RIP: 0010:drm_wait_one_vblank+0x1ef/0x210 [drm]
[ 2152.148456] Code: fe ff ff 48 8b 7b 08 4c 8b 6f 50 4d 85 ed 74 26 e8 56 1b 15 fb 44 89 e1 4c 89 ea 48 c7 c7 40 08 5e c0 48 89 c6 e8 e1 0b 77 fa <0f> 0b e9 7b fe ff ff 48 8b 1f eb 94 4c 8b 2f eb d5 e8 6b 2f 76 fb
[ 2152.148460] RSP: 0018:ffffab7dc5ffb5b0 EFLAGS: 00010246
[ 2152.148465] RAX: 0000000000000000 RBX: ffff91dbe6568000 RCX: 0000000000000000
[ 2152.148467] RDX: 0000000000000000 RSI: 0000000000000000 RDI: 0000000000000000
[ 2152.148469] RBP: ffffab7dc5ffb608 R08: 0000000000000000 R09: 0000000000000000
[ 2152.148471] R10: 0000000000000000 R11: 0000000000000000 R12: 0000000000000001
[ 2152.148472] R13: ffff91dbc2e33320 R14: 000000000004d106 R15: ffff91dbe6553960
[ 2152.148475] FS:  00007f4e55c2ba80(0000) GS:ffff91eb3d300000(0000) knlGS:0000000000000000
[ 2152.148479] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[ 2152.148481] CR2: 00000562786c7000 CR3: 0000000182a4e000 CR4: 0000000000750ee0
[ 2152.148484] PKRU: 55555554
[ 2152.148486] Call Trace:
[ 2152.148489]  <TASK>
[ 2152.148493]  ? show_regs+0x6d/0x80
[ 2152.148503]  ? __warn+0x89/0x160
[ 2152.148510]  ? drm_wait_one_vblank+0x1ef/0x210 [drm]
[ 2152.148592]  ? report_bug+0x17e/0x1b0
[ 2152.148600]  ? handle_bug+0x46/0x90
[ 2152.148609]  ? exc_invalid_op+0x18/0x80
[ 2152.148616]  ? asm_exc_invalid_op+0x1b/0x20
[ 2152.148626]  ? drm_wait_one_vblank+0x1ef/0x210 [drm]
[ 2152.148703]  ? __pfx_autoremove_wake_function+0x10/0x10
[ 2152.148714]  drm_crtc_wait_one_vblank+0x17/0x30 [drm]
[ 2152.148792]  intel_crtc_wait_for_next_vblank+0xe/0x20 [i915]
[ 2152.149173]  hsw_audio_codec_disable+0xf7/0x160 [i915]
[ 2152.149504]  intel_audio_codec_disable+0xb6/0x1d0 [i915]
[ 2152.149811]  intel_disable_ddi+0x101/0x1c0 [i915]
[ 2152.150097]  intel_encoders_disable+0x9b/0xd0 [i915]
[ 2152.150377]  hsw_crtc_disable+0x167/0x180 [i915]
[ 2152.150648]  intel_old_crtc_state_disables.constprop.0+0x38/0xa0 [i915]
[ 2152.150903]  intel_commit_modeset_disables+0x2a5/0x350 [i915]
[ 2152.151149]  ? intel_modeset_get_crtc_power_domains+0x8c/0xf0 [i915]
[ 2152.151397]  intel_atomic_commit_tail+0x190/0x920 [i915]
[ 2152.151631]  intel_atomic_commit+0x3bc/0x410 [i915]
[ 2152.151881]  drm_atomic_commit+0x96/0xd0 [drm]
[ 2152.151937]  ? __pfx___drm_printfn_info+0x10/0x10 [drm]
[ 2152.152041]  drm_client_modeset_commit_atomic+0x203/0x240 [drm]
[ 2152.152124]  drm_client_modeset_commit_locked+0x5b/0x170 [drm]
[ 2152.152189]  ? ttwu_queue_wakelist+0x135/0x1c0
[ 2152.152195]  __drm_fb_helper_restore_fbdev_mode_unlocked+0x86/0x100 [drm_kms_helper]
[ 2152.152232]  drm_fb_helper_set_par+0x2f/0x50 [drm_kms_helper]
[ 2152.152263]  intel_fbdev_set_par+0x1a/0x70 [i915]
[ 2152.152538]  fb_set_var+0x20a/0x460
[ 2152.152545]  ? set_next_entity+0xef/0x180
[ 2152.152550]  ? psi_group_change+0x219/0x530
[ 2152.152553]  ? pick_next_task_fair+0x395/0x5f0
[ 2152.152561]  fbcon_blank+0x24d/0x380
[ 2152.152569]  do_unblank_screen+0xc0/0x1c0
[ 2152.152575]  complete_change_console+0x67/0x150
[ 2152.152580]  vt_ioctl+0x484/0x9e0
[ 2152.152585]  tty_ioctl+0x2b8/0x8e0
[ 2152.152591]  ? do_syscall_64+0x67/0x90
[ 2152.152596]  ? syscall_exit_to_user_mode+0x29/0x50
[ 2152.152601]  ? do_syscall_64+0x67/0x90
[ 2152.152605]  ? __fget_light+0xa5/0x120
[ 2152.152612]  __x64_sys_ioctl+0x9d/0xe0
[ 2152.152617]  do_syscall_64+0x58/0x90
[ 2152.152622]  entry_SYSCALL_64_after_hwframe+0x72/0xdc
[ 2152.152627] RIP: 0033:0x7f4e55b1aaff
[ 2152.152634] Code: 00 48 89 44 24 18 31 c0 48 8d 44 24 60 c7 04 24 10 00 00 00 48 89 44 24 08 48 8d 44 24 20 48 89 44 24 10 b8 10 00 00 00 0f 05 <41> 89 c0 3d 00 f0 ff ff 77 1f 48 8b 44 24 18 64 48 2b 04 25 28 00
[ 2152.152637] RSP: 002b:00007ffe93fb5390 EFLAGS: 00000246 ORIG_RAX: 0000000000000010
[ 2152.152641] RAX: ffffffffffffffda RBX: 0000000000000001 RCX: 00007f4e55b1aaff
[ 2152.152644] RDX: 0000000000000001 RSI: 0000000000005605 RDI: 000000000000000e
[ 2152.152646] RBP: 000056540ba2c898 R08: 0000000000000002 R09: 00007ffe93fb51e0
[ 2152.152648] R10: 0000000000000000 R11: 0000000000000246 R12: 000056540ba2c940
[ 2152.152650] R13: 000056540ba2c894 R14: 000056540ba2c950 R15: 000056540ba2c948
[ 2152.152653]  </TASK>
[ 2152.152655] ---[ end trace 0000000000000000 ]---
[ 2177.698265] rfkill: input handler disabled
```

**Comment by leviport** [comment]
I've gotten two more freezes with bluetooth turned off completely, so I think we can rule that out. My oryp9 is currently in Hybrid mode, but I will try other graphics modes as well.

**Pull request closed without merging**
