### PR TITLE
Add audio quirks for pang10

### PR DESCRIPTION
**Pull request by crawfxrd**

### CODE REVIEW

**Review by jackpot51 — APPROVED** [review]

**Comment by leviport** [comment]
I'm still not seeing the prompt appear with this installed. I think the call has to be added in system76-driver, right?

**Comment by jackpot51** [comment]
@leviport it ought to be showing up without any change to system76-driver, unless it requires a different fixup

**Review by leviport — CHANGES_REQUESTED** [review]
I think it requires a different fixup then.

**Review by leviport — APPROVED** [review]
Works on pang10 and galp5. As long as you're satisfied with it on lemp10, I'm happy.

**Comment by jacobgkau** [comment]
Works on lemp10 as well.

**Pull request merged**
