### PR TITLE
Linux 5.17.4

### PR DESCRIPTION
**Pull request by jackpot51**
https://cdn.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.17.4

### CODE REVIEW

**Comment by leviport** [comment]
Looks like Aquantia ethernet on my desktop is not causing any problems with this kernel :tada:

**Comment by n3m0-22** [comment]
# Kernel Releases Tests

## `gaze15`

- [x] Updating to new kernel works with `apt update && apt upgrade`
  - [x] No new dependencies are required for kernel update
- [x] `system76-power` still operates as expected (across Intel/NVIDIA/switchable machines)
- [x] Mic in
- [x] Audio out:
  - [x] Laptop's built-in speakers
  - [x] Headphones
  - [x] Display Port
  - [x] HDMI
- [x] Video out via:
  - [x] DisplayPort
  - [x] HDMI
- [x] Suspend and resume:
  - [x] Switchable graphics laptops
    - [x] In Hybrid graphics mode
    - [x] In Nvidia graphics mode
    - [x] In Integrated graphics mode
  - [x] Nvidia desktop
  - [x] Integrated Intel desktop
  - [x] 150 suspend/resume cycles (`fwts s3 --s3-multiple 150`)
- [x] Graphics drivers included in the kernel (Intel/AMD)
  - [x] Switchable/hybrid graphics and graphics switching
- [x] Steam
  - [x] Steam installs via the Pop!_OS .deb in Pop!_Shop
  - [x] Steam launches from launcher
  - [x] Linux native game installs and runs
  - [x] Proton game installs and runs
- [x] Virtualbox installs and works as expected

**Comment by n3m0-22** [comment]
# Kernel Releases Tests

## `darp6`

- [x] Updating to new kernel works with `apt update && apt upgrade`
  - [x] No new dependencies are required for kernel update
- [x] Mic in
- [x] Audio out:
  - [x] Laptop's built-in speakers
  - [x] Headphones
  - [x] Display Port
  - [x] HDMI
- [x] Video out via:
  - [x] DisplayPort
  - [x] HDMI
- [x] Suspend and resume:
  - [x] Integrated Intel desktop
  - [x] 150 suspend/resume cycles (`fwts s3 --s3-multiple 150`)
- [x] Graphics drivers included in the kernel (Intel/AMD)
- [x] Steam
  - [x] Steam installs via the Pop!_OS .deb in Pop!_Shop
  - [x] Steam launches from launcher
  - [x] Linux native game installs and runs
  - [x] Proton game installs and runs
- [x] Virtualbox installs and works as expected

**Comment by jackpot51** [comment]
As usual, please test NVIDIA, VirtualBox, and ZFS DKMS packages

**Comment by jackpot51** [comment]
It was requested that we test that bluetooth audio is working.

**Comment by linuxgnuru** [comment]
Tested with kudu6; zfs, nvidia, and virtualbox worked fine and DKMS packages updated.

**Comment by n3m0-22** [comment]
The darp6 won't connect to two sets of bluetooth headphones, but will connect to and plays through a bluetooth speaker.

**Review by n3m0-22 — DISMISSED** [review]
The darp6 won't connect to two sets of bluetooth headphones, but will connect to and plays through a bluetooth speaker. 

*Update*
This may specific to the darp6 as both headphones and the speaker connected and played fine on the gaze15.

**Comment by linuxgnuru** [comment]
kudu6 is not resuming from suspend with power button; only way to wake is by closing and opening the lid

**Comment by jackpot51** [comment]
> kudu6 is not resuming from suspend with power button; only way to wake is by closing and opening the lid

Is this a regression?

**Comment by linuxgnuru** [comment]
Yes it is a regression. On clean install with 5.16.19 resume worked with the power button on the kudu6. 

Tested on pang11 and resume worked with both kernels so may be unique to the kudu

**Comment by n3m0-22** [comment]
@linuxgnuru Did you have the 510.68.02 driver installed as well when this suspend issues happened?

**Comment by jackpot51** [comment]
> Yes the 510 driver was installed but I was in integrated mode

Which 510 driver? If you are testing this change, it should be the one we have released, not one from another PR.

**Comment by linuxgnuru** [comment]
Sorry, it has the 510.60.02 from a clean install

**Comment by jackpot51** [comment]
> Sorry, it has the 510.60.02 from a clean install

Welp, since we have now released a newer NVIDIA driver, it might be worth trying it out

**Comment by jackpot51** [comment]
Obsolete, see #135. I'd recommend testing the kudu6 issue first.

**Pull request closed without merging**
