### PR TITLE
Linux 5.17.6

### PR DESCRIPTION
**Pull request by jackpot51**
Might want to check if https://bugzilla.kernel.org/show_bug.cgi?id=215768 is fixed

### CODE REVIEW

**Comment by bflanagin** [comment]
Initial tests on lemp9: Unit no longer suspends with or without blue-tooth devices.

**Comment by XV-02** [comment]
Ditto suspend failure on the Galp5-3050. Using the menu option to suspend, the screen blanks, but attempting to "resume" the screen wakes to a frozen session.

Log for a session which froze:
[5_17_6log.txt](https://github.com/pop-os/linux/files/8672837/5_17_6log.txt)
 
Closing the lid seems to work. The laptop sleeps, and wakes normally. Also works successfully from the command line.  However, it doesn't always recover a launch keyboard that was plugged in prior to sleep.

**Comment by bflanagin** [comment]
Possible workaround for bluetooth and suspend: @linuxgnuru suggested turning off bluetooth using rfkill before suspending, and then turning it back on after resume. Is it possible to add these commands to the suspend / resume cycle assuming they aren't already there?

**Comment by n3m0-22** [comment]
This fixed the suspend with bluetooth enable on the `gaze15` but not the `orpy4`.

**Comment by linuxgnuru** [comment]
tested thelio mira b1, mira b2, and kudu6. Thelio suspended/resumed without issue. kudu6 took ~20s to resume with bluetooth enabled; disabled resumed normally.

**Comment by n3m0-22** [comment]
`22.04` on `orpy4` results
[orpy4_5.17.6.txt](https://github.com/pop-os/linux/files/8682737/orpy4_5.17.6.txt)

**Comment by n3m0-22** [comment]
`22.04` on `darp6` results
[darp6_5.17.6.txt](https://github.com/pop-os/linux/files/8682816/darp6_5.17.6.txt)
Suspend and resume works intermittently with bluetooth enable and device paired.
Multiple failures for `fwts s3 --s3-multiple 150` running again with bluetooth off.

**Comment by n3m0-22** [comment]
`22.04` on `gaze15` results
[gaze15_5.17.6.txt](https://github.com/pop-os/linux/files/8682977/gaze15_5.17.6.txt)

Note: Mic in has not worked on any machines I have tested.

**Comment by jackpot51** [comment]
Obsolete, see #139

**Pull request closed without merging**
