### PR TITLE
Mixer-Maps: Add alternate ALC4080

### PR DESCRIPTION
**Pull request by 13r0ck**
Asus released motherboard(s) with an alternate ALC4080 that lacks
a SPDIF jack, and requires applying this map.

Requires https://github.com/pop-os/alsa-ucm-conf/pull/2

### CODE REVIEW

**Review by jackpot51 — APPROVED** [review]

**Comment by XV-02** [comment]
This is working for Mira-B1. Currently ensuring no regressions elsewhere.

**Review by jackpot51 — APPROVED** [review]

**Comment by jackpot51** [comment]
Since there are open kernel PRs (#154 and #152), if this passes it will need to be cherry-picked to those as well. I will do that once QA approves.

**Review by XV-02 — APPROVED** [review]
In concert with https://github.com/pop-os/libasound2/pull/1 and https://github.com/pop-os/alsa-ucm-conf/pull/2, this is both working, and not inducing any detectable regressions in other hardware.

**Comment by jackpot51** [comment]
Merged and cherry picked to the PRs

**Pull request merged**
