### PR TITLE
5 15 (21.10)

### PR DESCRIPTION
**Pull request by jackpot51**
The 5.15 kernel has a number of improvements for AMD CPUs and GPUs. Most of these improvements were backported to 5.14, but it would be good to target releasing this kernel since it will be a new upstream LTS kernel.

### CODE REVIEW

**Comment by brs17** [comment]
Quick testing feedback from @blakeridgway
> Everything with 5.15 is working on my Lemur Pro running 21.04. My thelio is another beast. My 5.15 Linux-headers busted and won’t install due to libc6 being outdated. Can’t update libc6 or i will lose pop-desktop.

**Comment by blakeridgway** [comment]
> Quick testing feedback from @blakeridgway
> 
> > Everything with 5.15 is working on my Lemur Pro running 21.04. My thelio is another beast. My 5.15 Linux-headers busted and won’t install due to libc6 being outdated. Can’t update libc6 or i will lose pop-desktop.

This is what I was met with when upgrading to 5.15; ONLY the linux-headers has provided any issues during the upgrade process. 

```
The following packages have unmet dependencies:
 linux-headers-5.15.0-051500-generic : Depends: libc6 (>= 2.34) but 2.33-0ubuntu5 is installed
```
Attached is the message I received when attempting to update libc6 to 2.34.
libc6

Since the fact that the 5.15 was more focused on working with 21.10+; I expected somethings the break when attempting to get it working on 21.04.

**Review by leviport — APPROVED** [review]
This looks good on Pop 21.10. I also tested ZFS on Pop 21.10 and Ubuntu 21.10 and both seem to be working fine.

**Review by crawfxrd — APPROVED** [review]

**Comment by jackpot51** [comment]
master_impish is now 5.15

**Pull request closed without merging**
