### PR TITLE
Linux 5.16.15

### PR DESCRIPTION
**Pull request by jackpot51**
Test with https://github.com/pop-os/linux-firmware/pull/19

Please test HP Dev One WiFi performance before and after.

### CODE REVIEW

**Comment by leviport** [comment]
This and https://github.com/pop-os/linux-firmware/pull/19 do seem to improve Dev One wifi performance a bit. 

Here's the speeds I was getting on 21.10 with 5.16.11 and the currently released linux-firmware:
```
Connecting to host 192.168.50.2, port 5201
[  5] local 192.168.50.15 port 33930 connected to 192.168.50.2 port 5201
[ ID] Interval           Transfer     Bitrate         Retr  Cwnd
[  5]   0.00-1.00   sec  59.1 MBytes   495 Mbits/sec    0   2.93 MBytes       
[  5]   1.00-2.00   sec  61.2 MBytes   514 Mbits/sec    0   3.08 MBytes       
[  5]   2.00-3.00   sec  63.8 MBytes   535 Mbits/sec    0   3.08 MBytes       
[  5]   3.00-4.00   sec  61.2 MBytes   514 Mbits/sec    0   3.08 MBytes       
[  5]   4.00-5.00   sec  61.2 MBytes   514 Mbits/sec    0   3.08 MBytes       
[  5]   5.00-6.00   sec  58.8 MBytes   493 Mbits/sec    0   3.08 MBytes       
[  5]   6.00-7.00   sec  61.2 MBytes   514 Mbits/sec    0   3.08 MBytes       
[  5]   7.00-8.00   sec  60.0 MBytes   503 Mbits/sec    0   3.08 MBytes       
[  5]   8.00-9.00   sec  50.0 MBytes   420 Mbits/sec    0   3.08 MBytes       
[  5]   9.00-10.00  sec  58.8 MBytes   493 Mbits/sec    0   3.08 MBytes       
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-10.00  sec   595 MBytes   499 Mbits/sec    0             sender
[  5]   0.00-10.02  sec   594 MBytes   497 Mbits/sec                  receiver

iperf Done.
```

And here's 5.16.15 + https://github.com/pop-os/linux-firmware/pull/19 on 21.10:
```
Connecting to host 192.168.50.2, port 5201
[  5] local 192.168.50.15 port 54686 connected to 192.168.50.2 port 5201
[ ID] Interval           Transfer     Bitrate         Retr  Cwnd
[  5]   0.00-1.00   sec  64.0 MBytes   537 Mbits/sec    0   3.02 MBytes       
[  5]   1.00-2.00   sec  67.5 MBytes   566 Mbits/sec    0   3.02 MBytes       
[  5]   2.00-3.00   sec  62.5 MBytes   524 Mbits/sec    0   3.02 MBytes       
[  5]   3.00-4.00   sec  62.5 MBytes   525 Mbits/sec    0   3.02 MBytes       
[  5]   4.00-5.00   sec  62.5 MBytes   524 Mbits/sec    0   3.02 MBytes       
[  5]   5.00-6.00   sec  60.0 MBytes   503 Mbits/sec    0   3.02 MBytes       
[  5]   6.00-7.00   sec  62.5 MBytes   525 Mbits/sec    0   3.02 MBytes       
[  5]   7.00-8.00   sec  62.5 MBytes   524 Mbits/sec    0   3.02 MBytes       
[  5]   8.00-9.00   sec  65.0 MBytes   545 Mbits/sec    0   3.02 MBytes       
[  5]   9.00-10.00  sec  65.0 MBytes   545 Mbits/sec    0   3.02 MBytes       
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-10.00  sec   634 MBytes   532 Mbits/sec    0             sender
[  5]   0.00-9.99   sec   634 MBytes   532 Mbits/sec                  receiver

iperf Done.
```

I ran that test ~10-15 times each, and just grabbed one that seemed relatively average for each set of runs.

**Comment by XV-02** [comment]
# Pop 20.04

- [x] Updating to new kernel works with `apt update && apt upgrade`
    - [x] No new dependencies are required for kernel update
- [x] `system76-power` still opperates as expected (across Intel/NVIDIA/switchable machines)
- [x] Mic in
- [x] Audio out:
    - [X] Laptop's built-in speakers
    - [x] Headphones
    - [ ] Display Port
    - [x] HDMI
- [x] Video out via:
    - [ ] DisplayPort
    - [x] HDMI
- [x] Thunderbolt docking station:
    - [x] HDMI and DisplayPort
    - [x] External storage device
    - [x] Networking
- [ ] Suspend and resume:
    - [X] Switchable graphics laptops 
        - [x] In Hybrid graphics mode
        - [x] In Nvidia graphics mode
        - [x] In Integrated graphics mode
    - [x] Nvidia desktop
    - [x] Discrete AMD desktop
    - [x] Integrated Intel desktop
    - [x] Integrated AMD desktop
    - [x] 150 suspend/resume cycles (`fwts s3 --s3-multiple 150`)
- [x] Graphics drivers included in the kernel (Intel/AMD)
    - [x] Switchable/hybrid graphics and graphics switching
- [x] Steam
    - [x] Steam installs via the Pop!_OS .deb in Pop!_Shop
    - [x] Steam launches from launcher
    - [x] Linux native game installs and runs
    - [x] Proton game installs and runs
- [X] Virtualbox installs and works as expected

# Pop 21.10

- [x] Updating to new kernel works with `apt update && apt upgrade`
    - [x] No new dependencies are required for kernel update
- [x] `system76-power` still opperates as expected (across Intel/NVIDIA/switchable machines)
- [x] Mic in
- [ ] Audio out:
    - [x] Laptop's built-in speakers
    - [x] Headphones
    - [ ] Display Port
    - [x] HDMI
- [x] Video out via:
    - [ ] DisplayPort
    - [x] HDMI
- [x] Thunderbolt docking station:
    - [x] HDMI and DisplayPort
    - [x] External storage device
    - [x] Networking
- [ ] Suspend and resume:
    - [x] Switchable graphics laptops 
        - [x] In Hybrid graphics mode
        - [x] In Nvidia graphics mode
            - Nvidia resume bug present.
        - [x] In Integrated graphics mode
    - [x] Nvidia desktop
    - [x] Discrete AMD desktop
    - [x] Integrated Intel desktop
    - [x] Integrated AMD desktop
    - [x] 150 suspend/resume cycles (`fwts s3 --s3-multiple 150`)
- [x] Graphics drivers included in the kernel (Intel/AMD)
    - [x] Switchable/hybrid graphics and graphics switching
- [x] Steam
    - [x] Steam installs via the Pop!_OS .deb in Pop!_Shop
    - [x] Steam launches from launcher
    - [x] Linux native game installs and runs
    - [X] Proton game installs and runs
- [x] Virtualbox installs and works as expected

# Pop 22.04

- [x] Updating to new kernel works with `apt update && apt upgrade`
    - [x] No new dependencies are required for kernel update
- [x] `system76-power` still opperates as expected (across Intel/NVIDIA/switchable machines)
- [x] Mic in
- [x] Audio out:
    - [x] Laptop's built-in speakers
    - [x] Headphones
    - [x] Display Port
    - [x] HDMI
- [x] Video out via:
    - [ ] DisplayPort
    - [x] HDMI
- [x] Thunderbolt docking station:
    - [x] HDMI and DisplayPort
    - [x] External storage device
    - [x] Networking
- [ ] Suspend and resume:
    - [x] Switchable graphics laptops 
        - [x] In Hybrid graphics mode
        - [x] In Nvidia graphics mode
        - [x] In Integrated graphics mode
    - [x] Nvidia desktop
    - [x] Discrete AMD desktop
    - [x] Integrated Intel desktop
    - [x] Integrated AMD desktop
    - [x] 150 suspend/resume cycles (`fwts s3 --s3-multiple 150`)
- [x] Graphics drivers included in the kernel (Intel/AMD)
    - [x] Switchable/hybrid graphics and graphics switching
- [x] Steam
    - [x] Steam installs via the Pop!_OS .deb in Pop!_Shop
    - [x] Steam launches from launcher
    - [x] Linux native game installs and runs
    - [x] Proton game installs and runs
- [x] Virtualbox installs and works as expected

**Comment by XV-02** [comment]
Ubuntu 20.04 does not correctly work over display port out with a Gaze16 3050Ti. With the displays extended or mirrored, the external display shows a solid purple colour and will display nothing other than the mouse cursor (which is renders correctly - that is with a hand when dragging a window, with a normal arrow cursor for general use, with a text carrot for text.) 

# Ubuntu 20.04

- [x] Updating to new kernel works with `apt update && apt upgrade`
    - [x] No new dependencies are required for kernel update
- [x] `system76-power` still opperates as expected (across Intel/NVIDIA/switchable machines)
- [x] Mic in
- [x] Audio out:
    - [x] Laptop's built-in speakers
    - [x] Headphones
    - [ ] Display Port
    - [x] HDMI
- [x] Video out via:
    - [ ] DisplayPort
    - [x] HDMI
- [x] Thunderbolt docking station:
    - [x] HDMI and DisplayPort
    - [x] External storage device
    - [x] Networking
- [x] Suspend and resume:
    - [x] Switchable graphics laptops 
        - [x] In Hybrid graphics mode
        - [x] In Nvidia graphics mode
            - Nvidia resume bug present
        - [x] In Integrated graphics mode
    - [x] Nvidia desktop
    - [x] Discrete AMD desktop
    - [x] Integrated Intel desktop
    - [x] Integrated AMD desktop
    - [x] 150 suspend/resume cycles (`fwts s3 --s3-multiple 150`)
- [x] Graphics drivers included in the kernel (Intel/AMD)
    - [x] Switchable/hybrid graphics and graphics switching
- [x] Steam
    - [ ] Steam installs via the Pop!_OS .deb in Pop!_Shop
    - [x] Steam launches from launcher
    - [x] Linux native game installs and runs
    - [X] Proton game installs and runs
- [x] Virtualbox installs and works as expected

**Comment by jackpot51** [comment]
Is this ready to go?

**Comment by jackpot51** [comment]
@13r0ck is going to do some more debugging on this. Is the linux-firmware PR okay?

**Comment by XV-02** [comment]
The Ubuntu 20.04 second screen issue seems tied to nvidia laptops.

**Comment by XV-02** [comment]
Since merging the https://github.com/pop-os/linux-firmware/pull/19 I cannot replicate the nvidia laptop issue.

**Review by XV-02 — APPROVED** [review]
I can no longer generate the nvidia laptop issue, and suspect that there was an issue with the two installations I was testing on (both were back to back and processed the same way, and a slip-up would have effected both)

Consequently, I am comfortable moving forward with this as it's passed our standard checks and nothing else anomalous presented itself.

**Pull request merged**
