### PR TITLE
Linux 6.3.7

### PR DESCRIPTION
**Pull request by 13r0ck**

### CODE REVIEW

**Review by leviport — CHANGES_REQUESTED** [review]
I'm seeing the same freezing behavior that I saw on 6.3: https://github.com/pop-os/linux/pull/251#issuecomment-1523732347

I'll get some log output the next time I get a chance. Should probably also check this on the other oryp9, and maybe another Alder Lake laptop.

**Comment by XV-02** [comment]
Given 6.4 being released, combined with issues with 6.3 freezing, and the regressions tied to 6.3 and nouveau, is it worth closing this PR and beginning to look towards testing and shipping a 6.4 kernel?

**Comment by XV-02** [comment]
@mmstick Given 6.4's release, combined with issues with 6.3 freezing, and the regressions tied to 6.3 and nouveau, is it worth closing this PR and beginning to look towards testing and shipping a 6.4 kernel?

**Comment by pktiuk** [comment]
> to look towards testing and shipping a 6.4 kernel?

@XV-02 There is PR for this https://github.com/pop-os/linux/pull/263

**Pull request closed without merging**
