### PR TITLE
Linux 6.4.6

### PR DESCRIPTION
**Pull request by mmstick**
Supersedes #266 

Required by https://github.com/pop-os/amd64-microcode/pull/2

### CODE REVIEW

**Review by jackpot51 — APPROVED** [review]

**Comment by leviport** [comment]
I've been running this on my oryp9 with a USB-C docking monitor since yesterday. The freezing problem seems far less prevalent, but I did see one freeze just a little bit ago. This time, the freeze was preceded by applications slowing down and feeling "choppy" for a few minutes, before the external display froze completely, then the built-in display froze a little bit after that. I'll continue to test and see if that was just a one-off.

**Comment by leviport** [comment]
Just got another one:
```
Jul 27 17:35:51 levioryx kernel: i915 0000:00:02.0: [drm] *ERROR* Atomic update failure on pipe B (start=27225 end=27226) time 123 us, min 1415, max 1439, scanline start 1411, end 1441
Jul 27 17:36:34 levioryx kernel: i915 0000:00:02.0: [drm] *ERROR* Atomic update failure on pipe B (start=34185 end=34186) time 126 us, min 1415, max 1439, scanline start 1412, end 1441
Jul 27 17:37:28 levioryx kernel: i915 0000:00:02.0: [drm] *ERROR* Atomic update failure on pipe B (start=43217 end=43218) time 228 us, min 1415, max 1439, scanline start 1389, end 1443
Jul 27 17:37:47 levioryx kernel: i915 0000:00:02.0: [drm] *ERROR* [CRTC:131:pipe B] flip_done timed out
Jul 27 17:37:57 levioryx kernel: i915 0000:00:02.0: [drm] *ERROR* flip_done timed out
Jul 27 17:37:57 levioryx kernel: i915 0000:00:02.0: [drm] *ERROR* [CRTC:131:pipe B] commit wait timed out
Jul 27 17:38:07 levioryx kernel: i915 0000:00:02.0: [drm] *ERROR* flip_done timed out
Jul 27 17:38:07 levioryx kernel: i915 0000:00:02.0: [drm] *ERROR* [PLANE:82:plane 1B] commit wait timed out
```

So I guess it waits for me to say something optimistic, then it really gives me the business.

**Comment by jackpot51** [comment]
@leviport providing Intel with logs here might help: https://gitlab.freedesktop.org/drm/intel/-/issues/8421

**Comment by XV-02** [comment]
As an addendum - I'm seeing what I'd call inconsistent behaviour on systems when upgrading to 6.4.6.

On Mira R3 w/ a discrete Radeon RX 5700, I initially saw issues with system shutdown (it was hanging at the point when KVM is busy stopping) but couldn't replicate the issue either across several reinstall.

On the Pang12 I use as a work machine, installing it seems to have interfered at some level with detection of hot plug events for displays. I disconnected an HDMI display, and the system was under the impression that it was still attached. I manually switched to single display mode, but even after that, I could switch back to join-displays despite no external display. On a reboot, it failed to detect a display being plugged in and stubbornly stayed in single display mode. This was not an issue after switching into COSMIC and then returning to Pop on Wayland. I need to this more though. 

The Slack desktop app seems not to work with the new kernel. While not part of our checklist, it is notable. Web-Slack works fine, as does VSCodium. So not sure what the disconnect is. Did grab the journal logs, though I've not looked at them yet. 
[646Journal.log](https://github.com/pop-os/linux/files/12202625/646Journal.log)

**Comment by pktiuk** [comment]
`6.4.7` is already out

**Review by leviport — APPROVED** [review]
Since this has some pretty big security fixes, I'm going to approve it for release despite the known freezing regression. We can work on a fix for that further down the line. The rest of our testing went well.

For anyone who starts experiencing freezes, I've found that switching to TTY3 and back to TTY2 usually fixes it, but it takes a good ~20 seconds before it switches to TTY3. Sometimes I need to hit Ctrl + Alt + F3 multiple times. But it eventually switches, and my desktop is unstuck once I switch back to TTY2. 

I also wasn't able to reproduce this issue with a USB-C to DisplayPort cable, so a minor adjustment in setup should bring relief, if the freezing becomes too infuriating.

**Comment by imfulee** [comment]
Coming from the [reddit announcement](https://www.reddit.com/r/pop_os/comments/15hb9l2/linux_646_and_mesa_2313_released/) of the new kernel release. 
As someone who didn't know how to switch from tty3 to tty2, I'm adding a comment here for anyone that doesn't know the exact steps.

- `Ctrl + Alt + F3` to switch to tty3
- `Ctrl + Alt + F2` to switch to tty2

**Comment by Cod3Bende4** [comment]
I am using latest 6.4.6 still facing same issues. When i shut down the computer, my screen goes black, keypad lights also goes off. But to start the computer again when i click power button, it does not boots up so i have to long press the power button to initiate a restart. It means my computer never shut down properly. I think this issue should be reopened. 

Let me know if you need any additional info

`Linux pop-os 6.4.6-76060406-generic #202307241739~1694621917~22.04~ac5e1a8 SMP PREEMPT_DYNAMIC Wed S x86_64 x86_64 x86_64 GNU/Linux`

**Pull request merged**
